<?php

declare(strict_types=1);

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Lang;
use Symfony\Component\HttpFoundation\Response;

class EnsurePublicFrenchTranslations
{
    public function handle(Request $request, Closure $next): Response
    {
        $supportedLocales = config('localizer.supported_locales', [
            'ar', 'en', 'fr', 'es', 'de', 'it', 'pt', 'ru', 'zh', 'ja', 'tr', 'hi', 'ko', 'nl', 'id',
        ]);

        $requestedLocale = strtolower((string) $request->segment(1));
        $locale = in_array($requestedLocale, $supportedLocales, true)
            ? $requestedLocale
            : app()->getLocale();

        if (! in_array($locale, $supportedLocales, true)) {
            return $next($request);
        }

        // These pages are central public entry points. Their Blade files already
        // resolve copy through landing.* / messages.* keys; this middleware fills
        // the keys that older locale files inherit from English so they never leak
        // untranslated signup/login copy to a supported locale.
        $translations = [
            'ar' => [
                'landing.signup_hero_line1' => 'أنشئ حسابك و',
                'landing.signup_hero_line2' => 'ابدأ خلال دقائق',
                'landing.signup_hero_sub' => 'كل ما تحتاجه لاستقبال الحجوزات وإدارة العملاء.',
                'landing.signup_benefit_1' => 'حجوزات عبر الإنترنت',
                'landing.signup_benefit_2' => 'متوافق مع الجوال',
                'landing.signup_benefit_3' => 'تذكيرات تلقائية',
                'landing.signup_benefit_4' => 'تحليلات وتقارير',
                'landing.signup_benefit_5' => 'دعم متعدد اللغات',
                'landing.signup_benefit_6' => 'بيانات آمنة',
                'landing.signup_what_happens_title' => 'ماذا يحدث بعد ذلك',
                'landing.signup_step1_title' => 'تجربة مجانية لمدة :days يومًا',
                'landing.signup_step1_desc' => 'احصل على وصول كامل إلى جميع الميزات خلال فترة التجربة.',
                'landing.signup_step2_title' => 'فترة سماح',
                'landing.signup_step2_desc' => 'اختر خطة للحفاظ على حسابك نشطًا بعد انتهاء التجربة.',
                'landing.signup_step3_title' => 'وضع القراءة فقط',
                'landing.signup_step3_desc' => 'يصبح حسابك محدودًا إذا لم يتم اختيار خطة.',
                'landing.signup_social_proof' => 'أكثر من 2,400 نشاط تجاري يديرون حجوزاتهم بالفعل على Velora.',
                'landing.signup_back' => 'العودة للرئيسية',
                'landing.signup_form_title' => 'أنشئ حساب نشاطك التجاري',
                'landing.signup_form_sub' => 'ابدأ تجربتك المجانية لمدة :days يومًا — لا تحتاج بطاقة ائتمانية.',
                'landing.signup_business_name' => 'اسم النشاط التجاري',
                'landing.signup_booking_slug' => 'رابط الحجز',
                'landing.signup_booking_slug_hint' => 'هذا هو الرابط الذي سيستخدمه عملاؤك للحجز معك.',
                'landing.signup_email' => 'البريد الإلكتروني',
                'landing.signup_password' => 'كلمة المرور',
                'landing.signup_password_hint' => '8 أحرف على الأقل.',
                'landing.signup_password_confirmation' => 'تأكيد كلمة المرور',
                'landing.signup_country' => 'الدولة',
                'landing.signup_admin_locale' => 'لغة لوحة التحكم',
                'landing.signup_terms_prefix' => 'أوافق على',
                'landing.signup_terms' => 'شروط الخدمة',
                'landing.signup_and' => 'و',
                'landing.signup_privacy' => 'سياسة الخصوصية',
                'landing.signup_coupon_question' => 'هل لديك رمز ترويجي؟',
                'landing.signup_coupon_placeholder' => 'أدخل الرمز',
                'landing.signup_submit' => 'إنشاء حسابي',
                'landing.signup_existing' => 'لديك حساب بالفعل؟',
                'landing.signup_login' => 'تسجيل الدخول',
                'landing.signup_isolated_data' => 'بياناتك معزولة في قاعدة بيانات خاصة ومخصصة — ولا تتم مشاركتها مع أي نشاط تجاري آخر.',
                'landing.signup_type_salon' => 'صالون',
                'landing.signup_type_barber' => 'حلاق',
                'landing.signup_type_clinic' => 'عيادة',
                'landing.signup_type_spa' => 'سبا',
                'landing.signup_type_gym' => 'نادي رياضي',
                'landing.signup_type_restaurant' => 'مطعم',
                'landing.signup_type_studio' => 'استوديو',
                'landing.signup_type_school' => 'مدرسة',
                'landing.signup_type_other' => 'أخرى',
                'landing.back_to_home' => 'العودة للرئيسية',
                'landing.nav_features' => 'المميزات',
                'landing.nav_how_it_works' => 'كيف تعمل المنصة',
                'landing.nav_pricing' => 'الأسعار',
                'landing.nav_company_admin_sign_in' => 'تسجيل دخول مسؤول النشاط',
                'landing.nav_start_trial' => 'ابدأ التجربة المجانية',
                'landing.switcher_lang_label' => 'تغيير اللغة',
                'landing.dark_mode' => 'الوضع الداكن',
                'landing.footer_rights' => 'جميع الحقوق محفوظة.',
            ],
            'fr' => [
                'landing.signup_hero_line1' => 'Créez votre compte et',
                'landing.signup_hero_line2' => 'commencez en quelques minutes',
                'landing.signup_hero_sub' => 'Tout ce dont vous avez besoin pour accepter les réservations et gérer vos clients.',
                'landing.signup_benefit_1' => 'Réservations en ligne',
                'landing.signup_benefit_2' => 'Compatible avec les mobiles',
                'landing.signup_benefit_3' => 'Rappels automatiques',
                'landing.signup_benefit_4' => 'Analyses et rapports',
                'landing.signup_benefit_5' => 'Prise en charge multilingue',
                'landing.signup_benefit_6' => 'Données sécurisées',
                'landing.signup_what_happens_title' => 'Et ensuite ?',
                'landing.signup_step1_title' => 'Essai gratuit de :days jours',
                'landing.signup_step1_desc' => 'Bénéficiez d’un accès complet à toutes les fonctionnalités pendant votre essai.',
                'landing.signup_step2_title' => 'Période de grâce',
                'landing.signup_step2_desc' => 'Choisissez une formule pour garder votre compte actif après l’essai.',
                'landing.signup_step3_title' => 'Mode lecture seule',
                'landing.signup_step3_desc' => 'Votre compte devient limité si aucune formule n’est sélectionnée.',
                'landing.signup_social_proof' => 'Plus de 2 400 entreprises gèrent déjà leurs réservations sur Velora.',
                'landing.signup_back' => 'Retour à l’accueil',
                'landing.signup_form_title' => 'Créez votre compte professionnel',
                'landing.signup_form_sub' => 'Commencez votre essai gratuit de :days jours — aucune carte bancaire requise.',
                'landing.signup_business_name' => 'Nom de l’entreprise',
                'landing.signup_booking_slug' => 'Lien de réservation',
                'landing.signup_booking_slug_hint' => 'C’est le lien que vos clients utiliseront pour prendre rendez-vous avec vous.',
                'landing.signup_email' => 'Adresse e-mail',
                'landing.signup_password' => 'Mot de passe',
                'landing.signup_password_hint' => '8 caractères minimum.',
                'landing.signup_password_confirmation' => 'Confirmer le mot de passe',
                'landing.signup_country' => 'Pays',
                'landing.signup_admin_locale' => 'Langue du tableau de bord',
                'landing.signup_terms_prefix' => 'J’accepte les',
                'landing.signup_terms' => 'Conditions générales d’utilisation',
                'landing.signup_and' => 'et la',
                'landing.signup_privacy' => 'Politique de confidentialité',
                'landing.signup_coupon_question' => 'Vous avez un code promotionnel ?',
                'landing.signup_coupon_placeholder' => 'Saisissez le code',
                'landing.signup_submit' => 'Créer mon compte',
                'landing.signup_existing' => 'Vous avez déjà un compte ?',
                'landing.signup_login' => 'Se connecter',
                'landing.signup_isolated_data' => 'Vos données sont isolées dans une base de données privée et dédiée — elles ne sont jamais partagées avec d’autres entreprises.',
                'landing.signup_type_salon' => 'Salon',
                'landing.signup_type_barber' => 'Barbershop',
                'landing.signup_type_clinic' => 'Clinique',
                'landing.signup_type_spa' => 'Spa',
                'landing.signup_type_gym' => 'Salle de sport',
                'landing.signup_type_restaurant' => 'Restaurant',
                'landing.signup_type_studio' => 'Studio',
                'landing.signup_type_school' => 'École',
                'landing.signup_type_other' => 'Autre',
                'landing.back_to_home' => 'Retour à l’accueil',
                'landing.nav_features' => 'Fonctionnalités',
                'landing.nav_how_it_works' => 'Comment ça marche',
                'landing.nav_pricing' => 'Tarifs',
                'landing.nav_company_admin_sign_in' => 'Connexion administrateur de l’entreprise',
                'landing.nav_start_trial' => 'Commencer l’essai gratuit',
                'landing.switcher_lang_label' => 'Changer de langue',
                'landing.dark_mode' => 'Mode sombre',
                'landing.footer_rights' => 'Tous droits réservés.',
            ],
            'es' => [
                'landing.signup_hero_line1' => 'Crea tu cuenta y',
                'landing.signup_hero_line2' => 'empieza en minutos',
                'landing.signup_hero_sub' => 'Todo lo que necesitas para aceptar reservas y gestionar clientes.',
                'landing.signup_benefit_1' => 'Reservas online', 'landing.signup_benefit_2' => 'Compatible con móviles', 'landing.signup_benefit_3' => 'Recordatorios automáticos', 'landing.signup_benefit_4' => 'Analítica e informes', 'landing.signup_benefit_5' => 'Soporte multilingüe', 'landing.signup_benefit_6' => 'Datos seguros',
                'landing.signup_what_happens_title' => '¿Qué pasa después?', 'landing.signup_step1_title' => 'Prueba gratis de :days días', 'landing.signup_step1_desc' => 'Accede a todas las funciones durante la prueba.', 'landing.signup_step2_title' => 'Periodo de gracia', 'landing.signup_step2_desc' => 'Elige un plan para mantener tu cuenta activa después de la prueba.', 'landing.signup_step3_title' => 'Modo de solo lectura', 'landing.signup_step3_desc' => 'Tu cuenta queda limitada si no eliges un plan.', 'landing.signup_social_proof' => 'Más de 2.400 negocios ya gestionan sus reservas con Velora.', 'landing.signup_back' => 'Volver al inicio', 'landing.signup_form_title' => 'Crea tu cuenta de empresa', 'landing.signup_form_sub' => 'Inicia tu prueba gratis de :days días — no necesitas tarjeta de crédito.', 'landing.signup_business_name' => 'Nombre del negocio', 'landing.signup_booking_slug' => 'Enlace de reserva', 'landing.signup_booking_slug_hint' => 'Este es el enlace que usarán tus clientes para reservar contigo.', 'landing.signup_email' => 'Correo electrónico', 'landing.signup_password' => 'Contraseña', 'landing.signup_password_hint' => 'Al menos 8 caracteres.', 'landing.signup_password_confirmation' => 'Confirmar contraseña', 'landing.signup_country' => 'País', 'landing.signup_admin_locale' => 'Idioma del panel', 'landing.signup_terms_prefix' => 'Acepto los', 'landing.signup_terms' => 'Términos del servicio', 'landing.signup_and' => 'y la', 'landing.signup_privacy' => 'Política de privacidad', 'landing.signup_coupon_question' => '¿Tienes un código promocional?', 'landing.signup_coupon_placeholder' => 'Introduce el código', 'landing.signup_submit' => 'Crear mi cuenta', 'landing.signup_existing' => '¿Ya tienes una cuenta?', 'landing.signup_login' => 'Iniciar sesión', 'landing.signup_isolated_data' => 'Tus datos están aislados en una base de datos privada y dedicada — nunca se comparten con otros negocios.', 'landing.signup_type_salon' => 'Salón', 'landing.signup_type_barber' => 'Barbería', 'landing.signup_type_clinic' => 'Clínica', 'landing.signup_type_spa' => 'Spa', 'landing.signup_type_gym' => 'Gimnasio', 'landing.signup_type_restaurant' => 'Restaurante', 'landing.signup_type_studio' => 'Estudio', 'landing.signup_type_school' => 'Escuela', 'landing.signup_type_other' => 'Otro',
            ],
            'de' => [
                'landing.signup_hero_line1' => 'Erstellen Sie Ihr Konto und', 'landing.signup_hero_line2' => 'starten Sie in wenigen Minuten', 'landing.signup_hero_sub' => 'Alles, was Sie brauchen, um Buchungen anzunehmen und Kunden zu verwalten.', 'landing.signup_benefit_1' => 'Online-Buchungen', 'landing.signup_benefit_2' => 'Mobilfreundlich', 'landing.signup_benefit_3' => 'Automatische Erinnerungen', 'landing.signup_benefit_4' => 'Analysen und Berichte', 'landing.signup_benefit_5' => 'Mehrsprachige Unterstützung', 'landing.signup_benefit_6' => 'Sichere Daten', 'landing.signup_what_happens_title' => 'Wie geht es weiter?', 'landing.signup_step1_title' => ':days Tage kostenlos testen', 'landing.signup_step1_desc' => 'Voller Zugriff auf alle Funktionen während der Testphase.', 'landing.signup_step2_title' => 'Kulanzzeit', 'landing.signup_step2_desc' => 'Wählen Sie einen Tarif, um Ihr Konto aktiv zu halten.', 'landing.signup_step3_title' => 'Nur-Lese-Modus', 'landing.signup_step3_desc' => 'Ihr Konto wird eingeschränkt, wenn kein Tarif ausgewählt wird.', 'landing.signup_social_proof' => 'Mehr als 2.400 Unternehmen verwalten ihre Buchungen bereits mit Velora.', 'landing.signup_back' => 'Zurück zur Startseite', 'landing.signup_form_title' => 'Erstellen Sie Ihr Geschäftskonto', 'landing.signup_form_sub' => 'Starten Sie Ihre :days-tägige kostenlose Testphase — keine Kreditkarte erforderlich.', 'landing.signup_business_name' => 'Name des Unternehmens', 'landing.signup_booking_slug' => 'Buchungslink', 'landing.signup_booking_slug_hint' => 'Über diesen Link können Ihre Kunden bei Ihnen buchen.', 'landing.signup_email' => 'E-Mail-Adresse', 'landing.signup_password' => 'Passwort', 'landing.signup_password_hint' => 'Mindestens 8 Zeichen.', 'landing.signup_password_confirmation' => 'Passwort bestätigen', 'landing.signup_country' => 'Land', 'landing.signup_admin_locale' => 'Sprache des Dashboards', 'landing.signup_terms_prefix' => 'Ich stimme den', 'landing.signup_terms' => 'Nutzungsbedingungen', 'landing.signup_and' => 'und der', 'landing.signup_privacy' => 'Datenschutzerklärung', 'landing.signup_coupon_question' => 'Haben Sie einen Promo-Code?', 'landing.signup_coupon_placeholder' => 'Code eingeben', 'landing.signup_submit' => 'Konto erstellen', 'landing.signup_existing' => 'Sie haben bereits ein Konto?', 'landing.signup_login' => 'Anmelden', 'landing.signup_isolated_data' => 'Ihre Daten sind in einer privaten, dedizierten Datenbank isoliert — sie werden niemals mit anderen Unternehmen geteilt.', 'landing.signup_type_salon' => 'Salon', 'landing.signup_type_barber' => 'Barbershop', 'landing.signup_type_clinic' => 'Klinik', 'landing.signup_type_spa' => 'Spa', 'landing.signup_type_gym' => 'Fitnessstudio', 'landing.signup_type_restaurant' => 'Restaurant', 'landing.signup_type_studio' => 'Studio', 'landing.signup_type_school' => 'Schule', 'landing.signup_type_other' => 'Andere',
            ],
            'it' => [
                'landing.signup_hero_line1' => 'Crea il tuo account e', 'landing.signup_hero_line2' => 'inizia in pochi minuti', 'landing.signup_hero_sub' => 'Tutto ciò che ti serve per accettare prenotazioni e gestire i clienti.', 'landing.signup_benefit_1' => 'Prenotazioni online', 'landing.signup_benefit_2' => 'Ottimizzato per mobile', 'landing.signup_benefit_3' => 'Promemoria automatici', 'landing.signup_benefit_4' => 'Analisi e report', 'landing.signup_benefit_5' => 'Supporto multilingue', 'landing.signup_benefit_6' => 'Dati sicuri', 'landing.signup_what_happens_title' => 'Cosa succede dopo?', 'landing.signup_step1_title' => 'Prova gratuita di :days giorni', 'landing.signup_step1_desc' => 'Accesso completo a tutte le funzioni durante la prova.', 'landing.signup_step2_title' => 'Periodo di tolleranza', 'landing.signup_step2_desc' => 'Scegli un piano per mantenere attivo il tuo account.', 'landing.signup_step3_title' => 'Modalità di sola lettura', 'landing.signup_step3_desc' => 'L’account viene limitato se non viene scelto alcun piano.', 'landing.signup_social_proof' => 'Oltre 2.400 attività gestiscono già le proprie prenotazioni con Velora.', 'landing.signup_back' => 'Torna alla home', 'landing.signup_form_title' => 'Crea il tuo account aziendale', 'landing.signup_form_sub' => 'Inizia la prova gratuita di :days giorni — non è richiesta alcuna carta di credito.', 'landing.signup_business_name' => 'Nome dell’attività', 'landing.signup_booking_slug' => 'Link di prenotazione', 'landing.signup_booking_slug_hint' => 'Questo è il link che i tuoi clienti useranno per prenotare con te.', 'landing.signup_email' => 'Indirizzo e-mail', 'landing.signup_password' => 'Password', 'landing.signup_password_hint' => 'Almeno 8 caratteri.', 'landing.signup_password_confirmation' => 'Conferma password', 'landing.signup_country' => 'Paese', 'landing.signup_admin_locale' => 'Lingua della dashboard', 'landing.signup_terms_prefix' => 'Accetto i', 'landing.signup_terms' => 'Termini di servizio', 'landing.signup_and' => 'e la', 'landing.signup_privacy' => 'Privacy Policy', 'landing.signup_coupon_question' => 'Hai un codice promozionale?', 'landing.signup_coupon_placeholder' => 'Inserisci il codice', 'landing.signup_submit' => 'Crea il mio account', 'landing.signup_existing' => 'Hai già un account?', 'landing.signup_login' => 'Accedi', 'landing.signup_isolated_data' => 'I tuoi dati sono isolati in un database privato e dedicato — non vengono mai condivisi con altre attività.', 'landing.signup_type_salon' => 'Salone', 'landing.signup_type_barber' => 'Barbiere', 'landing.signup_type_clinic' => 'Clinica', 'landing.signup_type_spa' => 'Spa', 'landing.signup_type_gym' => 'Palestra', 'landing.signup_type_restaurant' => 'Ristorante', 'landing.signup_type_studio' => 'Studio', 'landing.signup_type_school' => 'Scuola', 'landing.signup_type_other' => 'Altro',
            ],
            'pt' => [
                'landing.signup_hero_line1' => 'Crie a sua conta e', 'landing.signup_hero_line2' => 'comece em poucos minutos', 'landing.signup_hero_sub' => 'Tudo o que precisa para aceitar reservas e gerir clientes.', 'landing.signup_benefit_1' => 'Reservas online', 'landing.signup_benefit_2' => 'Compatível com dispositivos móveis', 'landing.signup_benefit_3' => 'Lembretes automáticos', 'landing.signup_benefit_4' => 'Análises e relatórios', 'landing.signup_benefit_5' => 'Suporte multilíngue', 'landing.signup_benefit_6' => 'Dados seguros', 'landing.signup_what_happens_title' => 'O que acontece a seguir?', 'landing.signup_step1_title' => 'Teste grátis de :days dias', 'landing.signup_step1_desc' => 'Acesso completo a todas as funcionalidades durante o teste.', 'landing.signup_step2_title' => 'Período de carência', 'landing.signup_step2_desc' => 'Escolha um plano para manter a sua conta ativa.', 'landing.signup_step3_title' => 'Modo somente leitura', 'landing.signup_step3_desc' => 'A sua conta fica limitada se nenhum plano for escolhido.', 'landing.signup_social_proof' => 'Mais de 2.400 empresas já gerem as suas reservas com a Velora.', 'landing.signup_back' => 'Voltar ao início', 'landing.signup_form_title' => 'Crie a sua conta empresarial', 'landing.signup_form_sub' => 'Comece o seu teste grátis de :days dias — não é necessário cartão de crédito.', 'landing.signup_business_name' => 'Nome da empresa', 'landing.signup_booking_slug' => 'Link de reserva', 'landing.signup_booking_slug_hint' => 'Este é o link que os seus clientes usarão para fazer reservas consigo.', 'landing.signup_email' => 'Endereço de e-mail', 'landing.signup_password' => 'Palavra-passe', 'landing.signup_password_hint' => 'Pelo menos 8 caracteres.', 'landing.signup_password_confirmation' => 'Confirmar palavra-passe', 'landing.signup_country' => 'País', 'landing.signup_admin_locale' => 'Idioma do painel', 'landing.signup_terms_prefix' => 'Concordo com os', 'landing.signup_terms' => 'Termos de serviço', 'landing.signup_and' => 'e a', 'landing.signup_privacy' => 'Política de privacidade', 'landing.signup_coupon_question' => 'Tem um código promocional?', 'landing.signup_coupon_placeholder' => 'Introduza o código', 'landing.signup_submit' => 'Criar a minha conta', 'landing.signup_existing' => 'Já tem uma conta?', 'landing.signup_login' => 'Iniciar sessão', 'landing.signup_isolated_data' => 'Os seus dados estão isolados numa base de dados privada e dedicada — nunca são partilhados com outras empresas.', 'landing.signup_type_salon' => 'Salão', 'landing.signup_type_barber' => 'Barbearia', 'landing.signup_type_clinic' => 'Clínica', 'landing.signup_type_spa' => 'Spa', 'landing.signup_type_gym' => 'Ginásio', 'landing.signup_type_restaurant' => 'Restaurante', 'landing.signup_type_studio' => 'Estúdio', 'landing.signup_type_school' => 'Escola', 'landing.signup_type_other' => 'Outro',
            ],
            'ru' => [
                'landing.signup_hero_line1' => 'Создайте аккаунт и', 'landing.signup_hero_line2' => 'начните за несколько минут', 'landing.signup_hero_sub' => 'Всё необходимое для приёма бронирований и управления клиентами.', 'landing.signup_benefit_1' => 'Онлайн-бронирования', 'landing.signup_benefit_2' => 'Удобно на мобильных устройствах', 'landing.signup_benefit_3' => 'Автоматические напоминания', 'landing.signup_benefit_4' => 'Аналитика и отчёты', 'landing.signup_benefit_5' => 'Мультиязычная поддержка', 'landing.signup_benefit_6' => 'Защищённые данные', 'landing.signup_what_happens_title' => 'Что дальше?', 'landing.signup_step1_title' => 'Бесплатный пробный период :days дней', 'landing.signup_step1_desc' => 'Полный доступ ко всем функциям во время пробного периода.', 'landing.signup_step2_title' => 'Льготный период', 'landing.signup_step2_desc' => 'Выберите план, чтобы сохранить аккаунт активным.', 'landing.signup_step3_title' => 'Режим только для чтения', 'landing.signup_step3_desc' => 'Доступ станет ограниченным, если план не выбран.', 'landing.signup_social_proof' => 'Более 2 400 компаний уже управляют бронированиями в Velora.', 'landing.signup_back' => 'Вернуться на главную', 'landing.signup_form_title' => 'Создайте аккаунт компании', 'landing.signup_form_sub' => 'Начните бесплатную пробную версию на :days дней — банковская карта не требуется.', 'landing.signup_business_name' => 'Название компании', 'landing.signup_booking_slug' => 'Ссылка для бронирования', 'landing.signup_booking_slug_hint' => 'По этой ссылке ваши клиенты будут записываться к вам.', 'landing.signup_email' => 'Электронная почта', 'landing.signup_password' => 'Пароль', 'landing.signup_password_hint' => 'Не менее 8 символов.', 'landing.signup_password_confirmation' => 'Подтвердите пароль', 'landing.signup_country' => 'Страна', 'landing.signup_admin_locale' => 'Язык панели управления', 'landing.signup_terms_prefix' => 'Я принимаю', 'landing.signup_terms' => 'Условия использования', 'landing.signup_and' => 'и', 'landing.signup_privacy' => 'Политику конфиденциальности', 'landing.signup_coupon_question' => 'Есть промокод?', 'landing.signup_coupon_placeholder' => 'Введите код', 'landing.signup_submit' => 'Создать аккаунт', 'landing.signup_existing' => 'Уже есть аккаунт?', 'landing.signup_login' => 'Войти', 'landing.signup_isolated_data' => 'Ваши данные изолированы в отдельной частной базе данных и никогда не передаются другим компаниям.', 'landing.signup_type_salon' => 'Салон', 'landing.signup_type_barber' => 'Барбершоп', 'landing.signup_type_clinic' => 'Клиника', 'landing.signup_type_spa' => 'Спа', 'landing.signup_type_gym' => 'Фитнес-клуб', 'landing.signup_type_restaurant' => 'Ресторан', 'landing.signup_type_studio' => 'Студия', 'landing.signup_type_school' => 'Школа', 'landing.signup_type_other' => 'Другое',
            ],
            'zh' => [
                'landing.signup_hero_line1' => '创建您的账户，', 'landing.signup_hero_line2' => '几分钟即可开始', 'landing.signup_hero_sub' => '接受预约和管理客户所需的一切功能。', 'landing.signup_benefit_1' => '在线预约', 'landing.signup_benefit_2' => '移动端友好', 'landing.signup_benefit_3' => '自动提醒', 'landing.signup_benefit_4' => '分析与报表', 'landing.signup_benefit_5' => '多语言支持', 'landing.signup_benefit_6' => '数据安全', 'landing.signup_what_happens_title' => '接下来会怎样？', 'landing.signup_step1_title' => '免费试用 :days 天', 'landing.signup_step1_desc' => '试用期间可完整使用所有功能。', 'landing.signup_step2_title' => '宽限期', 'landing.signup_step2_desc' => '选择方案以保持账户继续活跃。', 'landing.signup_step3_title' => '只读模式', 'landing.signup_step3_desc' => '未选择方案时，账户将受到限制。', 'landing.signup_social_proof' => '已有 2,400 多家企业在 Velora 上管理预约。', 'landing.signup_back' => '返回首页', 'landing.signup_form_title' => '创建您的企业账户', 'landing.signup_form_sub' => '开始 :days 天免费试用 — 无需信用卡。', 'landing.signup_business_name' => '企业名称', 'landing.signup_booking_slug' => '预约链接', 'landing.signup_booking_slug_hint' => '您的客户将通过此链接进行预约。', 'landing.signup_email' => '电子邮箱', 'landing.signup_password' => '密码', 'landing.signup_password_hint' => '至少 8 个字符。', 'landing.signup_password_confirmation' => '确认密码', 'landing.signup_country' => '国家/地区', 'landing.signup_admin_locale' => '后台语言', 'landing.signup_terms_prefix' => '我同意', 'landing.signup_terms' => '服务条款', 'landing.signup_and' => '和', 'landing.signup_privacy' => '隐私政策', 'landing.signup_coupon_question' => '有优惠码吗？', 'landing.signup_coupon_placeholder' => '输入优惠码', 'landing.signup_submit' => '创建我的账户', 'landing.signup_existing' => '已经有账户？', 'landing.signup_login' => '登录', 'landing.signup_isolated_data' => '您的数据存储在独立的私有数据库中，绝不会与其他企业共享。', 'landing.signup_type_salon' => '美容院', 'landing.signup_type_barber' => '理发店', 'landing.signup_type_clinic' => '诊所', 'landing.signup_type_spa' => '水疗中心', 'landing.signup_type_gym' => '健身房', 'landing.signup_type_restaurant' => '餐厅', 'landing.signup_type_studio' => '工作室', 'landing.signup_type_school' => '学校', 'landing.signup_type_other' => '其他',
            ],
            'ja' => [
                'landing.signup_hero_line1' => 'アカウントを作成して', 'landing.signup_hero_line2' => '数分で始めましょう', 'landing.signup_hero_sub' => '予約受付と顧客管理に必要なすべてが揃っています。', 'landing.signup_benefit_1' => 'オンライン予約', 'landing.signup_benefit_2' => 'モバイル対応', 'landing.signup_benefit_3' => '自動リマインダー', 'landing.signup_benefit_4' => '分析とレポート', 'landing.signup_benefit_5' => '多言語対応', 'landing.signup_benefit_6' => '安全なデータ', 'landing.signup_what_happens_title' => '次に何が起こりますか？', 'landing.signup_step1_title' => ':days日間の無料トライアル', 'landing.signup_step1_desc' => 'トライアル中はすべての機能を利用できます。', 'landing.signup_step2_title' => '猶予期間', 'landing.signup_step2_desc' => 'プランを選択してアカウントをアクティブに保ちます。', 'landing.signup_step3_title' => '読み取り専用モード', 'landing.signup_step3_desc' => 'プランを選択しない場合、アカウントが制限されます。', 'landing.signup_social_proof' => 'すでに2,400社以上の企業がVeloraで予約を管理しています。', 'landing.signup_back' => 'ホームに戻る', 'landing.signup_form_title' => 'ビジネスアカウントを作成', 'landing.signup_form_sub' => ':days日間の無料トライアルを開始 — クレジットカード不要。', 'landing.signup_business_name' => 'ビジネス名', 'landing.signup_booking_slug' => '予約リンク', 'landing.signup_booking_slug_hint' => 'お客様があなたのサービスを予約するためのリンクです。', 'landing.signup_email' => 'メールアドレス', 'landing.signup_password' => 'パスワード', 'landing.signup_password_hint' => '8文字以上。', 'landing.signup_password_confirmation' => 'パスワードを確認', 'landing.signup_country' => '国', 'landing.signup_admin_locale' => 'ダッシュボードの言語', 'landing.signup_terms_prefix' => '同意します：', 'landing.signup_terms' => '利用規約', 'landing.signup_and' => 'および', 'landing.signup_privacy' => 'プライバシーポリシー', 'landing.signup_coupon_question' => 'プロモーションコードをお持ちですか？', 'landing.signup_coupon_placeholder' => 'コードを入力', 'landing.signup_submit' => 'アカウントを作成', 'landing.signup_existing' => 'すでにアカウントをお持ちですか？', 'landing.signup_login' => 'ログイン', 'landing.signup_isolated_data' => 'データは専用のプライベートデータベースに分離され、他の企業と共有されることはありません。', 'landing.signup_type_salon' => 'サロン', 'landing.signup_type_barber' => '理容室', 'landing.signup_type_clinic' => 'クリニック', 'landing.signup_type_spa' => 'スパ', 'landing.signup_type_gym' => 'ジム', 'landing.signup_type_restaurant' => 'レストラン', 'landing.signup_type_studio' => 'スタジオ', 'landing.signup_type_school' => '学校', 'landing.signup_type_other' => 'その他',
            ],
            'tr' => [
                'landing.signup_hero_line1' => 'Hesabınızı oluşturun ve', 'landing.signup_hero_line2' => 'dakikalar içinde başlayın', 'landing.signup_hero_sub' => 'Randevuları kabul etmek ve müşterileri yönetmek için ihtiyacınız olan her şey.', 'landing.signup_benefit_1' => 'Online randevular', 'landing.signup_benefit_2' => 'Mobil uyumlu', 'landing.signup_benefit_3' => 'Otomatik hatırlatmalar', 'landing.signup_benefit_4' => 'Analiz ve raporlar', 'landing.signup_benefit_5' => 'Çoklu dil desteği', 'landing.signup_benefit_6' => 'Güvenli veriler', 'landing.signup_what_happens_title' => 'Sırada ne var?', 'landing.signup_step1_title' => ':days günlük ücretsiz deneme', 'landing.signup_step1_desc' => 'Deneme boyunca tüm özelliklere tam erişim elde edin.', 'landing.signup_step2_title' => 'Ek süre', 'landing.signup_step2_desc' => 'Hesabınızı aktif tutmak için bir plan seçin.', 'landing.signup_step3_title' => 'Salt okunur mod', 'landing.signup_step3_desc' => 'Plan seçilmezse hesabınız kısıtlanır.', 'landing.signup_social_proof' => '2.400’den fazla işletme randevularını Velora ile yönetiyor.', 'landing.signup_back' => 'Ana sayfaya dön', 'landing.signup_form_title' => 'İşletme hesabınızı oluşturun', 'landing.signup_form_sub' => ':days günlük ücretsiz denemenizi başlatın — kredi kartı gerekmez.', 'landing.signup_business_name' => 'İşletme adı', 'landing.signup_booking_slug' => 'Rezervasyon bağlantısı', 'landing.signup_booking_slug_hint' => 'Müşterilerinizin sizinle rezervasyon yapmak için kullanacağı bağlantıdır.', 'landing.signup_email' => 'E-posta adresi', 'landing.signup_password' => 'Şifre', 'landing.signup_password_hint' => 'En az 8 karakter.', 'landing.signup_password_confirmation' => 'Şifreyi onayla', 'landing.signup_country' => 'Ülke', 'landing.signup_admin_locale' => 'Kontrol paneli dili', 'landing.signup_terms_prefix' => 'Kabul ediyorum:', 'landing.signup_terms' => 'Hizmet Şartları', 'landing.signup_and' => 've', 'landing.signup_privacy' => 'Gizlilik Politikası', 'landing.signup_coupon_question' => 'Promosyon kodunuz var mı?', 'landing.signup_coupon_placeholder' => 'Kodu girin', 'landing.signup_submit' => 'Hesabımı oluştur', 'landing.signup_existing' => 'Zaten hesabınız var mı?', 'landing.signup_login' => 'Giriş yap', 'landing.signup_isolated_data' => 'Verileriniz özel ve ayrılmış bir veritabanında izole edilir — diğer işletmelerle asla paylaşılmaz.', 'landing.signup_type_salon' => 'Salon', 'landing.signup_type_barber' => 'Berber', 'landing.signup_type_clinic' => 'Klinik', 'landing.signup_type_spa' => 'Spa', 'landing.signup_type_gym' => 'Spor salonu', 'landing.signup_type_restaurant' => 'Restoran', 'landing.signup_type_studio' => 'Stüdyo', 'landing.signup_type_school' => 'Okul', 'landing.signup_type_other' => 'Diğer',
            ],
            'hi' => [
                'landing.signup_hero_line1' => 'अपना खाता बनाएं और', 'landing.signup_hero_line2' => 'कुछ ही मिनटों में शुरू करें', 'landing.signup_hero_sub' => 'बुकिंग लेने और ग्राहकों को प्रबंधित करने के लिए आपकी सभी ज़रूरतें एक जगह।', 'landing.signup_benefit_1' => 'ऑनलाइन बुकिंग', 'landing.signup_benefit_2' => 'मोबाइल के लिए अनुकूल', 'landing.signup_benefit_3' => 'स्वचालित रिमाइंडर', 'landing.signup_benefit_4' => 'विश्लेषण और रिपोर्ट', 'landing.signup_benefit_5' => 'बहुभाषी सहायता', 'landing.signup_benefit_6' => 'सुरक्षित डेटा', 'landing.signup_what_happens_title' => 'आगे क्या होगा?', 'landing.signup_step1_title' => ':days दिनों का निःशुल्क ट्रायल', 'landing.signup_step1_desc' => 'ट्रायल के दौरान सभी सुविधाओं का पूरा उपयोग करें।', 'landing.signup_step2_title' => 'ग्रेस अवधि', 'landing.signup_step2_desc' => 'खाता सक्रिय रखने के लिए एक योजना चुनें।', 'landing.signup_step3_title' => 'केवल-पठन मोड', 'landing.signup_step3_desc' => 'योजना न चुनने पर आपका खाता सीमित हो जाएगा।', 'landing.signup_social_proof' => '2,400 से अधिक व्यवसाय पहले ही Velora पर अपनी बुकिंग चला रहे हैं।', 'landing.signup_back' => 'होम पर वापस जाएं', 'landing.signup_form_title' => 'अपना बिज़नेस अकाउंट बनाएं', 'landing.signup_form_sub' => ':days दिनों का निःशुल्क ट्रायल शुरू करें — क्रेडिट कार्ड की आवश्यकता नहीं।', 'landing.signup_business_name' => 'व्यवसाय का नाम', 'landing.signup_booking_slug' => 'बुकिंग लिंक', 'landing.signup_booking_slug_hint' => 'यही लिंक आपके ग्राहक आपके साथ बुकिंग के लिए उपयोग करेंगे।', 'landing.signup_email' => 'ईमेल पता', 'landing.signup_password' => 'पासवर्ड', 'landing.signup_password_hint' => 'कम से कम 8 अक्षर।', 'landing.signup_password_confirmation' => 'पासवर्ड की पुष्टि करें', 'landing.signup_country' => 'देश', 'landing.signup_admin_locale' => 'डैशबोर्ड भाषा', 'landing.signup_terms_prefix' => 'मैं सहमत हूँ', 'landing.signup_terms' => 'सेवा की शर्तों', 'landing.signup_and' => 'और', 'landing.signup_privacy' => 'गोपनीयता नीति', 'landing.signup_coupon_question' => 'क्या आपके पास प्रोमो कोड है?', 'landing.signup_coupon_placeholder' => 'कोड दर्ज करें', 'landing.signup_submit' => 'मेरा खाता बनाएं', 'landing.signup_existing' => 'क्या आपके पास पहले से खाता है?', 'landing.signup_login' => 'साइन इन करें', 'landing.signup_isolated_data' => 'आपका डेटा एक निजी, समर्पित डेटाबेस में अलग रखा जाता है — इसे कभी भी अन्य व्यवसायों के साथ साझा नहीं किया जाता।', 'landing.signup_type_salon' => 'सैलून', 'landing.signup_type_barber' => 'बार्बरशॉप', 'landing.signup_type_clinic' => 'क्लिनिक', 'landing.signup_type_spa' => 'स्पा', 'landing.signup_type_gym' => 'जिम', 'landing.signup_type_restaurant' => 'रेस्तरां', 'landing.signup_type_studio' => 'स्टूडियो', 'landing.signup_type_school' => 'स्कूल', 'landing.signup_type_other' => 'अन्य',
            ],
            'ko' => [
                'landing.signup_hero_line1' => '계정을 만들고', 'landing.signup_hero_line2' => '몇 분 만에 시작하세요', 'landing.signup_hero_sub' => '예약 접수와 고객 관리를 위해 필요한 모든 기능을 제공합니다.', 'landing.signup_benefit_1' => '온라인 예약', 'landing.signup_benefit_2' => '모바일 친화적', 'landing.signup_benefit_3' => '자동 알림', 'landing.signup_benefit_4' => '분석 및 리포트', 'landing.signup_benefit_5' => '다국어 지원', 'landing.signup_benefit_6' => '안전한 데이터', 'landing.signup_what_happens_title' => '다음 단계는 무엇인가요?', 'landing.signup_step1_title' => ':days일 무료 체험', 'landing.signup_step1_desc' => '체험 기간 동안 모든 기능을 제한 없이 이용하세요.', 'landing.signup_step2_title' => '유예 기간', 'landing.signup_step2_desc' => '계정을 계속 활성 상태로 유지하려면 요금제를 선택하세요.', 'landing.signup_step3_title' => '읽기 전용 모드', 'landing.signup_step3_desc' => '요금제를 선택하지 않으면 계정이 제한됩니다.', 'landing.signup_social_proof' => '2,400개 이상의 기업이 이미 Velora에서 예약을 관리하고 있습니다.', 'landing.signup_back' => '홈으로 돌아가기', 'landing.signup_form_title' => '비즈니스 계정 만들기', 'landing.signup_form_sub' => ':days일 무료 체험을 시작하세요 — 신용카드가 필요하지 않습니다.', 'landing.signup_business_name' => '비즈니스 이름', 'landing.signup_booking_slug' => '예약 링크', 'landing.signup_booking_slug_hint' => '고객이 예약할 때 사용하는 링크입니다.', 'landing.signup_email' => '이메일 주소', 'landing.signup_password' => '비밀번호', 'landing.signup_password_hint' => '8자 이상.', 'landing.signup_password_confirmation' => '비밀번호 확인', 'landing.signup_country' => '국가', 'landing.signup_admin_locale' => '대시보드 언어', 'landing.signup_terms_prefix' => '다음에 동의합니다:', 'landing.signup_terms' => '서비스 약관', 'landing.signup_and' => '및', 'landing.signup_privacy' => '개인정보 처리방침', 'landing.signup_coupon_question' => '프로모션 코드가 있나요?', 'landing.signup_coupon_placeholder' => '코드 입력', 'landing.signup_submit' => '내 계정 만들기', 'landing.signup_existing' => '이미 계정이 있으신가요?', 'landing.signup_login' => '로그인', 'landing.signup_isolated_data' => '고객님의 데이터는 전용 비공개 데이터베이스에 격리되며 다른 비즈니스와 공유되지 않습니다.', 'landing.signup_type_salon' => '살롱', 'landing.signup_type_barber' => '바버샵', 'landing.signup_type_clinic' => '클리닉', 'landing.signup_type_spa' => '스파', 'landing.signup_type_gym' => '헬스장', 'landing.signup_type_restaurant' => '레스토랑', 'landing.signup_type_studio' => '스튜디오', 'landing.signup_type_school' => '학교', 'landing.signup_type_other' => '기타',
            ],
            'nl' => [
                'landing.signup_hero_line1' => 'Maak je account aan en', 'landing.signup_hero_line2' => 'begin binnen enkele minuten', 'landing.signup_hero_sub' => 'Alles wat je nodig hebt om boekingen aan te nemen en klanten te beheren.', 'landing.signup_benefit_1' => 'Online boekingen', 'landing.signup_benefit_2' => 'Mobielvriendelijk', 'landing.signup_benefit_3' => 'Automatische herinneringen', 'landing.signup_benefit_4' => 'Analyses en rapporten', 'landing.signup_benefit_5' => 'Meertalige ondersteuning', 'landing.signup_benefit_6' => 'Veilige gegevens', 'landing.signup_what_happens_title' => 'Wat gebeurt er daarna?', 'landing.signup_step1_title' => ':days dagen gratis proberen', 'landing.signup_step1_desc' => 'Volledige toegang tot alle functies tijdens je proefperiode.', 'landing.signup_step2_title' => 'Coulanceperiode', 'landing.signup_step2_desc' => 'Kies een abonnement om je account actief te houden.', 'landing.signup_step3_title' => 'Alleen-lezenmodus', 'landing.signup_step3_desc' => 'Je account wordt beperkt als je geen abonnement kiest.', 'landing.signup_social_proof' => 'Meer dan 2.400 bedrijven beheren hun afspraken al met Velora.', 'landing.signup_back' => 'Terug naar home', 'landing.signup_form_title' => 'Maak je bedrijfsaccount aan', 'landing.signup_form_sub' => 'Start je gratis proefperiode van :days dagen — geen creditcard nodig.', 'landing.signup_business_name' => 'Bedrijfsnaam', 'landing.signup_booking_slug' => 'Boekingslink', 'landing.signup_booking_slug_hint' => 'Dit is de link die je klanten gebruiken om bij je te boeken.', 'landing.signup_email' => 'E-mailadres', 'landing.signup_password' => 'Wachtwoord', 'landing.signup_password_hint' => 'Minimaal 8 tekens.', 'landing.signup_password_confirmation' => 'Bevestig wachtwoord', 'landing.signup_country' => 'Land', 'landing.signup_admin_locale' => 'Dashboardtaal', 'landing.signup_terms_prefix' => 'Ik ga akkoord met de', 'landing.signup_terms' => 'Servicevoorwaarden', 'landing.signup_and' => 'en het', 'landing.signup_privacy' => 'Privacybeleid', 'landing.signup_coupon_question' => 'Heb je een promotiecode?', 'landing.signup_coupon_placeholder' => 'Voer code in', 'landing.signup_submit' => 'Mijn account maken', 'landing.signup_existing' => 'Heb je al een account?', 'landing.signup_login' => 'Inloggen', 'landing.signup_isolated_data' => 'Je gegevens zijn geïsoleerd in een privé, speciale database — ze worden nooit gedeeld met andere bedrijven.', 'landing.signup_type_salon' => 'Salon', 'landing.signup_type_barber' => 'Barbershop', 'landing.signup_type_clinic' => 'Kliniek', 'landing.signup_type_spa' => 'Spa', 'landing.signup_type_gym' => 'Sportschool', 'landing.signup_type_restaurant' => 'Restaurant', 'landing.signup_type_studio' => 'Studio', 'landing.signup_type_school' => 'School', 'landing.signup_type_other' => 'Anders',
            ],
            'id' => [
                'landing.signup_hero_line1' => 'Buat akun Anda dan', 'landing.signup_hero_line2' => 'mulai dalam beberapa menit', 'landing.signup_hero_sub' => 'Semua yang Anda butuhkan untuk menerima pemesanan dan mengelola pelanggan.', 'landing.signup_benefit_1' => 'Pemesanan online', 'landing.signup_benefit_2' => 'Ramah seluler', 'landing.signup_benefit_3' => 'Pengingat otomatis', 'landing.signup_benefit_4' => 'Analitik dan laporan', 'landing.signup_benefit_5' => 'Dukungan multibahasa', 'landing.signup_benefit_6' => 'Data aman', 'landing.signup_what_happens_title' => 'Apa yang terjadi selanjutnya?', 'landing.signup_step1_title' => 'Uji coba gratis :days hari', 'landing.signup_step1_desc' => 'Akses penuh ke semua fitur selama masa uji coba.', 'landing.signup_step2_title' => 'Masa tenggang', 'landing.signup_step2_desc' => 'Pilih paket untuk menjaga akun tetap aktif.', 'landing.signup_step3_title' => 'Mode hanya-baca', 'landing.signup_step3_desc' => 'Akun Anda akan dibatasi jika tidak memilih paket.', 'landing.signup_social_proof' => 'Lebih dari 2.400 bisnis sudah mengelola pemesanan mereka di Velora.', 'landing.signup_back' => 'Kembali ke beranda', 'landing.signup_form_title' => 'Buat akun bisnis Anda', 'landing.signup_form_sub' => 'Mulai uji coba gratis selama :days hari — kartu kredit tidak diperlukan.', 'landing.signup_business_name' => 'Nama bisnis', 'landing.signup_booking_slug' => 'Tautan pemesanan', 'landing.signup_booking_slug_hint' => 'Ini adalah tautan yang digunakan pelanggan untuk memesan layanan Anda.', 'landing.signup_email' => 'Alamat email', 'landing.signup_password' => 'Kata sandi', 'landing.signup_password_hint' => 'Minimal 8 karakter.', 'landing.signup_password_confirmation' => 'Konfirmasi kata sandi', 'landing.signup_country' => 'Negara', 'landing.signup_admin_locale' => 'Bahasa dasbor', 'landing.signup_terms_prefix' => 'Saya menyetujui', 'landing.signup_terms' => 'Ketentuan Layanan', 'landing.signup_and' => 'dan', 'landing.signup_privacy' => 'Kebijakan Privasi', 'landing.signup_coupon_question' => 'Punya kode promo?', 'landing.signup_coupon_placeholder' => 'Masukkan kode', 'landing.signup_submit' => 'Buat akun saya', 'landing.signup_existing' => 'Sudah punya akun?', 'landing.signup_login' => 'Masuk', 'landing.signup_isolated_data' => 'Data Anda diisolasi dalam basis data privat khusus — tidak pernah dibagikan dengan bisnis lain.', 'landing.signup_type_salon' => 'Salon', 'landing.signup_type_barber' => 'Barbershop', 'landing.signup_type_clinic' => 'Klinik', 'landing.signup_type_spa' => 'Spa', 'landing.signup_type_gym' => 'Gym', 'landing.signup_type_restaurant' => 'Restoran', 'landing.signup_type_studio' => 'Studio', 'landing.signup_type_school' => 'Sekolah', 'landing.signup_type_other' => 'Lainnya',
            ],
            'en' => [],
        ];

        Lang::addLines($translations[$locale] ?? [], $locale);

        if ($locale !== 'en') {
            $loginTranslations = [
                'ar' => ['messages.login' => 'تسجيل الدخول', 'messages.login_to_account' => 'سجّل الدخول إلى حسابك', 'messages.password' => 'كلمة المرور', 'messages.remember_me' => 'تذكرني', 'messages.loading' => 'جاري تسجيل الدخول...', 'messages.login_success' => 'تم تسجيل الدخول بنجاح.', 'messages.login_failed' => 'بيانات الدخول غير صحيحة.', '*.Toggle theme' => 'تغيير المظهر', '*.Back to workspace' => 'العودة لمساحة العمل'],
                'fr' => ['messages.login' => 'Connexion', 'messages.login_to_account' => 'Connectez-vous à votre compte', 'messages.password' => 'Mot de passe', 'messages.remember_me' => 'Se souvenir de moi', 'messages.loading' => 'Connexion...', 'messages.login_success' => 'Connexion réussie.', 'messages.login_failed' => 'Identifiants invalides.', '*.Toggle theme' => 'Changer de thème', '*.Back to workspace' => 'Retour à l’espace de travail'],
                'es' => ['messages.login' => 'Iniciar sesión', 'messages.login_to_account' => 'Inicia sesión en tu cuenta', 'messages.password' => 'Contraseña', 'messages.remember_me' => 'Recuérdame', 'messages.loading' => 'Iniciando sesión...', 'messages.login_success' => 'Inicio de sesión correcto.', 'messages.login_failed' => 'Credenciales no válidas.', '*.Toggle theme' => 'Cambiar tema', '*.Back to workspace' => 'Volver al espacio de trabajo'],
                'de' => ['messages.login' => 'Anmelden', 'messages.login_to_account' => 'Melden Sie sich bei Ihrem Konto an', 'messages.password' => 'Passwort', 'messages.remember_me' => 'Angemeldet bleiben', 'messages.loading' => 'Anmeldung...', 'messages.login_success' => 'Erfolgreich angemeldet.', 'messages.login_failed' => 'Ungültige Anmeldedaten.', '*.Toggle theme' => 'Design wechseln', '*.Back to workspace' => 'Zurück zum Arbeitsbereich'],
                'it' => ['messages.login' => 'Accedi', 'messages.login_to_account' => 'Accedi al tuo account', 'messages.password' => 'Password', 'messages.remember_me' => 'Ricordami', 'messages.loading' => 'Accesso...', 'messages.login_success' => 'Accesso riuscito.', 'messages.login_failed' => 'Credenziali non valide.', '*.Toggle theme' => 'Cambia tema', '*.Back to workspace' => 'Torna allo spazio di lavoro'],
                'pt' => ['messages.login' => 'Iniciar sessão', 'messages.login_to_account' => 'Inicie sessão na sua conta', 'messages.password' => 'Palavra-passe', 'messages.remember_me' => 'Lembrar-me', 'messages.loading' => 'A iniciar sessão...', 'messages.login_success' => 'Sessão iniciada com sucesso.', 'messages.login_failed' => 'Credenciais inválidas.', '*.Toggle theme' => 'Alterar tema', '*.Back to workspace' => 'Voltar ao espaço de trabalho'],
                'ru' => ['messages.login' => 'Войти', 'messages.login_to_account' => 'Войдите в свой аккаунт', 'messages.password' => 'Пароль', 'messages.remember_me' => 'Запомнить меня', 'messages.loading' => 'Вход...', 'messages.login_success' => 'Вход выполнен успешно.', 'messages.login_failed' => 'Неверные учетные данные.', '*.Toggle theme' => 'Сменить тему', '*.Back to workspace' => 'Вернуться в рабочее пространство'],
                'zh' => ['messages.login' => '登录', 'messages.login_to_account' => '登录您的账户', 'messages.password' => '密码', 'messages.remember_me' => '记住我', 'messages.loading' => '正在登录...', 'messages.login_success' => '登录成功。', 'messages.login_failed' => '账号或密码无效。', '*.Toggle theme' => '切换主题', '*.Back to workspace' => '返回工作区'],
                'ja' => ['messages.login' => 'ログイン', 'messages.login_to_account' => 'アカウントにログイン', 'messages.password' => 'パスワード', 'messages.remember_me' => 'ログイン状態を保持', 'messages.loading' => 'ログイン中...', 'messages.login_success' => 'ログインしました。', 'messages.login_failed' => '認証情報が正しくありません。', '*.Toggle theme' => 'テーマを切り替え', '*.Back to workspace' => 'ワークスペースに戻る'],
                'tr' => ['messages.login' => 'Giriş yap', 'messages.login_to_account' => 'Hesabınıza giriş yapın', 'messages.password' => 'Şifre', 'messages.remember_me' => 'Beni hatırla', 'messages.loading' => 'Giriş yapılıyor...', 'messages.login_success' => 'Giriş başarılı.', 'messages.login_failed' => 'Geçersiz kimlik bilgileri.', '*.Toggle theme' => 'Temayı değiştir', '*.Back to workspace' => 'Çalışma alanına dön'],
                'hi' => ['messages.login' => 'साइन इन करें', 'messages.login_to_account' => 'अपने खाते में साइन इन करें', 'messages.password' => 'पासवर्ड', 'messages.remember_me' => 'मुझे याद रखें', 'messages.loading' => 'साइन इन हो रहा है...', 'messages.login_success' => 'सफलतापूर्वक साइन इन हुआ।', 'messages.login_failed' => 'अमान्य लॉगिन विवरण।', '*.Toggle theme' => 'थीम बदलें', '*.Back to workspace' => 'वर्कस्पेस पर वापस जाएं'],
                'ko' => ['messages.login' => '로그인', 'messages.login_to_account' => '계정에 로그인하세요', 'messages.password' => '비밀번호', 'messages.remember_me' => '로그인 상태 유지', 'messages.loading' => '로그인 중...', 'messages.login_success' => '로그인되었습니다.', 'messages.login_failed' => '잘못된 인증 정보입니다.', '*.Toggle theme' => '테마 전환', '*.Back to workspace' => '워크스페이스로 돌아가기'],
                'nl' => ['messages.login' => 'Inloggen', 'messages.login_to_account' => 'Log in op je account', 'messages.password' => 'Wachtwoord', 'messages.remember_me' => 'Onthoud mij', 'messages.loading' => 'Inloggen...', 'messages.login_success' => 'Succesvol ingelogd.', 'messages.login_failed' => 'Ongeldige inloggegevens.', '*.Toggle theme' => 'Thema wijzigen', '*.Back to workspace' => 'Terug naar werkruimte'],
                'id' => ['messages.login' => 'Masuk', 'messages.login_to_account' => 'Masuk ke akun Anda', 'messages.password' => 'Kata sandi', 'messages.remember_me' => 'Ingat saya', 'messages.loading' => 'Sedang masuk...', 'messages.login_success' => 'Berhasil masuk.', 'messages.login_failed' => 'Kredensial tidak valid.', '*.Toggle theme' => 'Ganti tema', '*.Back to workspace' => 'Kembali ke ruang kerja'],
            ];

            Lang::addLines($loginTranslations[$locale] ?? [], $locale);
        }

        return $next($request);
    }
}
