<?php
return [
 'appointment_booked'=>['subject'=>'Подтверждение записи','greeting'=>'Здравствуйте, :name!','message'=>'Ваша запись успешно оформлена!','details'=>'Детали записи:','date'=>'Дата: :date','time'=>'Время: :time','tenant'=>'Клиника: :tenant','footer'=>'Спасибо, что пользуетесь нашими услугами!','sms'=>':name, вы записаны на :date в :time в :tenant'],
 'appointment_reminder'=>['subject'=>'Напоминание о записи','greeting'=>'Здравствуйте, :name!','message'=>'Напоминаем о вашей ближайшей записи!','details'=>'Детали записи:','date'=>'Дата: :date','time'=>'Время: :time','service'=>'Услуга: :service','staff'=>'Специалист: :staff','tenant'=>'Клиника: :tenant','queue'=>'Номер очереди: :number','reference'=>'Номер бронирования: :reference','tracking'=>'Отслеживать запись: :url','footer'=>'Будем рады вас видеть!','sms'=>'Напоминание: запись :date в :time в :tenant'],
 'appointment_cancelled'=>['subject'=>'Запись отменена','greeting'=>'Здравствуйте, :name!','message'=>'Ваша запись отменена.','details'=>'Детали отменённой записи:','date'=>'Дата: :date','time'=>'Время: :time','tenant'=>'Клиника: :tenant','footer'=>'Вы можете записаться снова в любое время.','sms'=>'Ваша запись :date в :time в :tenant отменена'],
 'appointment_confirmed'=>['subject'=>'Запись подтверждена','greeting'=>'Здравствуйте, :name!','message'=>'Ваша запись подтверждена!','details'=>'Детали записи:','date'=>'Дата: :date','time'=>'Время: :time','tenant'=>'Клиника: :tenant','footer'=>'Будем рады вас видеть!','sms'=>'Ваша запись :date в :time в :tenant подтверждена'],
 'queue_next'=>['subject'=>'Сейчас ваша очередь!','greeting'=>'Здравствуйте, :name!','message'=>'Сейчас ваша очередь! Подойдите к стойке.','queue_number'=>'Номер очереди: :number','footer'=>'Спасибо за ожидание!','sms'=>':name, сейчас ваша очередь! Номер: :number. Подойдите к стойке.'],
 'queue_position_update'=>['subject'=>'Обновление позиции в очереди','greeting'=>'Здравствуйте, :name!','message'=>'Обновление вашей позиции в очереди:','queue_number'=>'Номер очереди: :number','position'=>'Перед вами людей: :position','estimated_wait'=>'Ожидаемое время: :time минут','footer'=>'Спасибо за терпение!','sms'=>'Номер: :number, перед вами :position, ожидаемое время: :time минут'],
 'queue_ready'=>['subject'=>'Скоро ваша очередь','greeting'=>'Здравствуйте, :name!','message'=>'Приготовьтесь, скоро ваша очередь!','queue_number'=>'Номер очереди: :number','position'=>'Перед вами только 1 человек','footer'=>'Спасибо за ожидание!','sms'=>'Приготовьтесь! Номер: :number, перед вами только 1 человек.'],
 'queue_skipped'=>['subject'=>'Ваша очередь пропущена','greeting'=>'Здравствуйте, :name!','message'=>'Ваша очередь пропущена из-за отсутствия.','queue_number'=>'Номер очереди: :number','footer'=>'Вы можете получить новый номер у стойки.','sms'=>'Ваша очередь (номер :number) пропущена из-за отсутствия. Вы можете получить новый номер.'],
 'view_details'=>'Подробнее','thank_you'=>'Спасибо, что пользуетесь нашими услугами','regards'=>'С уважением',
];
