<?php
/**
 * One-time script: add pricing section translation keys to all 15 lang files.
 * Run from project root: php _add_pricing_keys.php
 */

$base = __DIR__ . '/lang';

// Keys per language — values are already properly escaped PHP single-quoted strings
$translations = [];

/* ─────────────── ENGLISH ─────────────── */
$translations['en'] = <<<'PHP'

    // Pricing section — index page
    'pricing_one_plan'        => 'One plan — all features — price adapts to your region.',
    'billing_save_months'     => 'Save 2 months',
    'billing_billed'          => 'Billed ',
    'pricing_platform'        => 'Full Platform',
    'pricing_trial_badge'     => ':days-day free trial',
    'pricing_per_mo'          => '/mo',
    'pricing_no_card_trial'   => 'No credit card for the free trial',
    'pricing_tax_badge'       => '— total',
    'pricing_tax_note'        => 'will be added at checkout. Total:',
    'pricing_methods_heading' => 'Payment methods',
    'pricing_money_back'      => '30-day money-back guarantee',
    'pricing_region_label'    => 'Region:',
    'pricing_change_region'   => 'Change',
    'pricing_no_fees_note'    => 'No credit card · Cancel anytime · No setup fees',
    'pricing_feat_scheduling' => 'Smart appointment scheduling',
    'pricing_feat_queue'      => 'Real-time digital queue',
    'pricing_feat_staff'      => 'Unlimited staff accounts',
    'pricing_feat_ratings'    => 'Customer ratings & feedback',
    'pricing_feat_analytics'  => 'Analytics & business reports',
    'pricing_feat_reminders'  => 'Automated SMS & email reminders',
    'pricing_feat_languages'  => '15 interface languages',
    'pricing_feat_onboarding' => 'Onboarding wizard',
    'pricing_feat_database'   => 'Isolated database per tenant',
    'pricing_feat_api'        => 'API access',
    'pricing_feat_booking'    => 'Custom booking page',
    'pricing_feat_support'    => 'Priority support',
    'pricing_after_trial'     => 'What happens after the trial?',
    'trial_full_access'       => 'Full Access',
    'trial_full_days'         => 'Days 1–:days',
    'trial_full_desc'         => 'All features unlocked. Email only. No card needed.',
    'trial_grace_title'       => 'Grace Period',
    'trial_grace_days'        => 'Days :start–:end',
    'trial_grace_desc'        => '3 extra days to choose a plan before restrictions kick in.',
    'trial_readonly_title'    => 'Read-Only Mode',
    'trial_readonly_day'      => 'Day :day+',
    'trial_readonly_desc'     => 'Nothing is deleted. Upgrade any time to restore full access.',
    'stat_businesses'         => 'Businesses',
    'stat_appointments'       => 'Appointments',
    'stat_countries'          => 'Countries',
    'registration_closed'     => 'Registration is currently closed. Check back soon.',
PHP;

/* ─────────────── ARABIC ─────────────── */
$translations['ar'] = <<<'PHP'

    // Pricing section — index page
    'pricing_one_plan'        => 'خطة واحدة — جميع المميزات — السعر يتكيف مع منطقتك.',
    'billing_save_months'     => 'وفّر شهرين',
    'billing_billed'          => 'يُفوتر ',
    'pricing_platform'        => 'المنصة الكاملة',
    'pricing_trial_badge'     => 'تجربة :days يوماً مجاناً',
    'pricing_per_mo'          => '/شهر',
    'pricing_no_card_trial'   => 'لا حاجة لبطاقة ائتمان للتجربة المجانية',
    'pricing_tax_badge'       => '— الإجمالي',
    'pricing_tax_note'        => 'سيُضاف عند الدفع. الإجمالي:',
    'pricing_methods_heading' => 'طرق الدفع',
    'pricing_money_back'      => 'ضمان استرداد المال خلال 30 يوماً',
    'pricing_region_label'    => 'المنطقة:',
    'pricing_change_region'   => 'تغيير',
    'pricing_no_fees_note'    => 'بدون بطاقة ائتمان · إلغاء في أي وقت · بدون رسوم إعداد',
    'pricing_feat_scheduling' => 'جدولة مواعيد ذكية',
    'pricing_feat_queue'      => 'طابور رقمي فوري',
    'pricing_feat_staff'      => 'حسابات موظفين غير محدودة',
    'pricing_feat_ratings'    => 'تقييمات العملاء وملاحظاتهم',
    'pricing_feat_analytics'  => 'تحليلات وتقارير الأعمال',
    'pricing_feat_reminders'  => 'تذكيرات SMS وبريد إلكتروني تلقائية',
    'pricing_feat_languages'  => '15 لغة للواجهة',
    'pricing_feat_onboarding' => 'معالج الإعداد',
    'pricing_feat_database'   => 'قاعدة بيانات معزولة لكل مستأجر',
    'pricing_feat_api'        => 'وصول للـ API',
    'pricing_feat_booking'    => 'صفحة حجز مخصصة',
    'pricing_feat_support'    => 'دعم ذو أولوية',
    'pricing_after_trial'     => 'ماذا يحدث بعد انتهاء التجربة؟',
    'trial_full_access'       => 'وصول كامل',
    'trial_full_days'         => 'الأيام 1–:days',
    'trial_full_desc'         => 'جميع المميزات متاحة. بريد إلكتروني فقط. لا بطاقة مطلوبة.',
    'trial_grace_title'       => 'فترة السماح',
    'trial_grace_days'        => 'الأيام :start–:end',
    'trial_grace_desc'        => '3 أيام إضافية لاختيار خطة قبل بدء القيود.',
    'trial_readonly_title'    => 'وضع القراءة فقط',
    'trial_readonly_day'      => 'اليوم :day+',
    'trial_readonly_desc'     => 'لا شيء يُحذف. قم بالترقية في أي وقت لاستعادة الوصول الكامل.',
    'stat_businesses'         => 'شركة',
    'stat_appointments'       => 'موعد',
    'stat_countries'          => 'دولة',
    'registration_closed'     => 'التسجيل مغلق حالياً. تحقق لاحقاً.',
PHP;

/* ─────────────── FRENCH ─────────────── */
$translations['fr'] = <<<'PHP'

    // Pricing section — index page
    'pricing_one_plan'        => 'Un plan — toutes les fonctionnalités — le prix s\'adapte à votre région.',
    'billing_save_months'     => 'Économisez 2 mois',
    'billing_billed'          => 'Facturé ',
    'pricing_platform'        => 'Plateforme complète',
    'pricing_trial_badge'     => 'Essai gratuit :days jours',
    'pricing_per_mo'          => '/mois',
    'pricing_no_card_trial'   => 'Pas de carte bancaire pour l\'essai gratuit',
    'pricing_tax_badge'       => '— total',
    'pricing_tax_note'        => 'sera ajouté au paiement. Total :',
    'pricing_methods_heading' => 'Méthodes de paiement',
    'pricing_money_back'      => 'Garantie remboursement 30 jours',
    'pricing_region_label'    => 'Région :',
    'pricing_change_region'   => 'Changer',
    'pricing_no_fees_note'    => 'Sans carte · Annulez quand vous voulez · Sans frais',
    'pricing_feat_scheduling' => 'Prise de rendez-vous intelligente',
    'pricing_feat_queue'      => 'File d\'attente numérique en temps réel',
    'pricing_feat_staff'      => 'Comptes employés illimités',
    'pricing_feat_ratings'    => 'Avis et retours clients',
    'pricing_feat_analytics'  => 'Analyses et rapports commerciaux',
    'pricing_feat_reminders'  => 'Rappels SMS et e-mail automatisés',
    'pricing_feat_languages'  => '15 langues d\'interface',
    'pricing_feat_onboarding' => 'Assistant d\'intégration',
    'pricing_feat_database'   => 'Base de données isolée par locataire',
    'pricing_feat_api'        => 'Accès API',
    'pricing_feat_booking'    => 'Page de réservation personnalisée',
    'pricing_feat_support'    => 'Support prioritaire',
    'pricing_after_trial'     => 'Que se passe-t-il après l\'essai ?',
    'trial_full_access'       => 'Accès complet',
    'trial_full_days'         => 'Jours 1–:days',
    'trial_full_desc'         => 'Toutes les fonctionnalités débloquées. E-mail uniquement. Pas de carte requise.',
    'trial_grace_title'       => 'Période de grâce',
    'trial_grace_days'        => 'Jours :start–:end',
    'trial_grace_desc'        => '3 jours supplémentaires pour choisir un plan avant les restrictions.',
    'trial_readonly_title'    => 'Mode lecture seule',
    'trial_readonly_day'      => 'Jour :day+',
    'trial_readonly_desc'     => 'Rien n\'est supprimé. Passez à la version payante à tout moment.',
    'stat_businesses'         => 'Entreprises',
    'stat_appointments'       => 'Rendez-vous',
    'stat_countries'          => 'Pays',
    'registration_closed'     => 'Inscriptions closes. Revenez bientôt.',
PHP;

/* ─────────────── GERMAN ─────────────── */
$translations['de'] = <<<'PHP'

    // Pricing section — index page
    'pricing_one_plan'        => 'Ein Plan — alle Funktionen — Preis passt sich Ihrer Region an.',
    'billing_save_months'     => '2 Monate sparen',
    'billing_billed'          => 'Abgerechnet ',
    'pricing_platform'        => 'Vollständige Plattform',
    'pricing_trial_badge'     => ':days-Tage kostenlose Testphase',
    'pricing_per_mo'          => '/Mo',
    'pricing_no_card_trial'   => 'Keine Kreditkarte für die Testphase erforderlich',
    'pricing_tax_badge'       => '— gesamt',
    'pricing_tax_note'        => 'wird beim Bezahlen hinzugefügt. Gesamt:',
    'pricing_methods_heading' => 'Zahlungsmethoden',
    'pricing_money_back'      => '30 Tage Geld-zurück-Garantie',
    'pricing_region_label'    => 'Region:',
    'pricing_change_region'   => 'Ändern',
    'pricing_no_fees_note'    => 'Keine Kreditkarte · Jederzeit kündbar · Keine Einrichtungsgebühren',
    'pricing_feat_scheduling' => 'Intelligente Terminplanung',
    'pricing_feat_queue'      => 'Digitale Warteschlange in Echtzeit',
    'pricing_feat_staff'      => 'Unbegrenzte Mitarbeiterkonten',
    'pricing_feat_ratings'    => 'Kundenbewertungen & Feedback',
    'pricing_feat_analytics'  => 'Analysen & Geschäftsberichte',
    'pricing_feat_reminders'  => 'Automatische SMS & E-Mail-Erinnerungen',
    'pricing_feat_languages'  => '15 Oberflächensprachen',
    'pricing_feat_onboarding' => 'Einrichtungsassistent',
    'pricing_feat_database'   => 'Isolierte Datenbank pro Mandant',
    'pricing_feat_api'        => 'API-Zugang',
    'pricing_feat_booking'    => 'Individuelle Buchungsseite',
    'pricing_feat_support'    => 'Prioritätssupport',
    'pricing_after_trial'     => 'Was passiert nach der Testphase?',
    'trial_full_access'       => 'Vollzugang',
    'trial_full_days'         => 'Tage 1–:days',
    'trial_full_desc'         => 'Alle Funktionen freigeschaltet. Nur E-Mail. Keine Karte erforderlich.',
    'trial_grace_title'       => 'Gnadenfrist',
    'trial_grace_days'        => 'Tage :start–:end',
    'trial_grace_desc'        => '3 zusätzliche Tage, um einen Plan zu wählen, bevor Einschränkungen greifen.',
    'trial_readonly_title'    => 'Nur-Lesen-Modus',
    'trial_readonly_day'      => 'Tag :day+',
    'trial_readonly_desc'     => 'Nichts wird gelöscht. Jederzeit upgraden, um vollen Zugriff wiederherzustellen.',
    'stat_businesses'         => 'Unternehmen',
    'stat_appointments'       => 'Termine',
    'stat_countries'          => 'Länder',
    'registration_closed'     => 'Registrierung derzeit geschlossen. Bitte später wiederkommen.',
PHP;

/* ─────────────── SPANISH ─────────────── */
$translations['es'] = <<<'PHP'

    // Pricing section — index page
    'pricing_one_plan'        => 'Un plan — todas las funciones — el precio se adapta a tu región.',
    'billing_save_months'     => 'Ahorra 2 meses',
    'billing_billed'          => 'Facturado ',
    'pricing_platform'        => 'Plataforma completa',
    'pricing_trial_badge'     => 'Prueba gratuita de :days días',
    'pricing_per_mo'          => '/mes',
    'pricing_no_card_trial'   => 'Sin tarjeta de crédito para la prueba gratuita',
    'pricing_tax_badge'       => '— total',
    'pricing_tax_note'        => 'se añadirá al pagar. Total:',
    'pricing_methods_heading' => 'Métodos de pago',
    'pricing_money_back'      => 'Garantía de devolución de 30 días',
    'pricing_region_label'    => 'Región:',
    'pricing_change_region'   => 'Cambiar',
    'pricing_no_fees_note'    => 'Sin tarjeta · Cancela cuando quieras · Sin tarifas de configuración',
    'pricing_feat_scheduling' => 'Programación inteligente de citas',
    'pricing_feat_queue'      => 'Cola digital en tiempo real',
    'pricing_feat_staff'      => 'Cuentas de personal ilimitadas',
    'pricing_feat_ratings'    => 'Valoraciones y comentarios de clientes',
    'pricing_feat_analytics'  => 'Análisis e informes de negocio',
    'pricing_feat_reminders'  => 'Recordatorios automáticos por SMS y correo',
    'pricing_feat_languages'  => '15 idiomas de interfaz',
    'pricing_feat_onboarding' => 'Asistente de incorporación',
    'pricing_feat_database'   => 'Base de datos aislada por inquilino',
    'pricing_feat_api'        => 'Acceso a API',
    'pricing_feat_booking'    => 'Página de reservas personalizada',
    'pricing_feat_support'    => 'Soporte prioritario',
    'pricing_after_trial'     => '¿Qué pasa después de la prueba?',
    'trial_full_access'       => 'Acceso completo',
    'trial_full_days'         => 'Días 1–:days',
    'trial_full_desc'         => 'Todas las funciones desbloqueadas. Solo correo. Sin tarjeta necesaria.',
    'trial_grace_title'       => 'Período de gracia',
    'trial_grace_days'        => 'Días :start–:end',
    'trial_grace_desc'        => '3 días extra para elegir un plan antes de que entren las restricciones.',
    'trial_readonly_title'    => 'Modo de solo lectura',
    'trial_readonly_day'      => 'Día :day+',
    'trial_readonly_desc'     => 'Nada se elimina. Actualiza en cualquier momento para restaurar el acceso.',
    'stat_businesses'         => 'Empresas',
    'stat_appointments'       => 'Citas',
    'stat_countries'          => 'Países',
    'registration_closed'     => 'Registro cerrado temporalmente. Vuelve pronto.',
PHP;

/* ─────────────── ITALIAN ─────────────── */
$translations['it'] = <<<'PHP'

    // Pricing section — index page
    'pricing_one_plan'        => 'Un piano — tutte le funzionalità — il prezzo si adatta alla tua regione.',
    'billing_save_months'     => 'Risparmia 2 mesi',
    'billing_billed'          => 'Fatturato ',
    'pricing_platform'        => 'Piattaforma completa',
    'pricing_trial_badge'     => 'Prova gratuita di :days giorni',
    'pricing_per_mo'          => '/mese',
    'pricing_no_card_trial'   => 'Nessuna carta di credito per la prova gratuita',
    'pricing_tax_badge'       => '— totale',
    'pricing_tax_note'        => 'verrà aggiunto al pagamento. Totale:',
    'pricing_methods_heading' => 'Metodi di pagamento',
    'pricing_money_back'      => 'Garanzia soddisfatti o rimborsati 30 giorni',
    'pricing_region_label'    => 'Regione:',
    'pricing_change_region'   => 'Cambia',
    'pricing_no_fees_note'    => 'Senza carta · Annulla quando vuoi · Senza costi di configurazione',
    'pricing_feat_scheduling' => 'Pianificazione appuntamenti intelligente',
    'pricing_feat_queue'      => 'Coda digitale in tempo reale',
    'pricing_feat_staff'      => 'Account staff illimitati',
    'pricing_feat_ratings'    => 'Valutazioni e feedback dei clienti',
    'pricing_feat_analytics'  => 'Analisi e report aziendali',
    'pricing_feat_reminders'  => 'Promemoria SMS ed e-mail automatizzati',
    'pricing_feat_languages'  => '15 lingue dell\'interfaccia',
    'pricing_feat_onboarding' => 'Procedura guidata di configurazione',
    'pricing_feat_database'   => 'Database isolato per tenant',
    'pricing_feat_api'        => 'Accesso API',
    'pricing_feat_booking'    => 'Pagina di prenotazione personalizzata',
    'pricing_feat_support'    => 'Supporto prioritario',
    'pricing_after_trial'     => 'Cosa succede dopo la prova?',
    'trial_full_access'       => 'Accesso completo',
    'trial_full_days'         => 'Giorni 1–:days',
    'trial_full_desc'         => 'Tutte le funzionalità sbloccate. Solo e-mail. Nessuna carta necessaria.',
    'trial_grace_title'       => 'Periodo di grazia',
    'trial_grace_days'        => 'Giorni :start–:end',
    'trial_grace_desc'        => '3 giorni extra per scegliere un piano prima delle restrizioni.',
    'trial_readonly_title'    => 'Modalità sola lettura',
    'trial_readonly_day'      => 'Giorno :day+',
    'trial_readonly_desc'     => 'Nulla viene eliminato. Esegui l\'upgrade in qualsiasi momento.',
    'stat_businesses'         => 'Aziende',
    'stat_appointments'       => 'Appuntamenti',
    'stat_countries'          => 'Paesi',
    'registration_closed'     => 'Registrazioni chiuse al momento. Ricontrolla presto.',
PHP;

/* ─────────────── PORTUGUESE ─────────────── */
$translations['pt'] = <<<'PHP'

    // Pricing section — index page
    'pricing_one_plan'        => 'Um plano — todas as funcionalidades — o preço adapta-se à sua região.',
    'billing_save_months'     => 'Poupe 2 meses',
    'billing_billed'          => 'Faturado ',
    'pricing_platform'        => 'Plataforma completa',
    'pricing_trial_badge'     => 'Teste gratuito de :days dias',
    'pricing_per_mo'          => '/mês',
    'pricing_no_card_trial'   => 'Sem cartão de crédito para o teste gratuito',
    'pricing_tax_badge'       => '— total',
    'pricing_tax_note'        => 'será adicionado no pagamento. Total:',
    'pricing_methods_heading' => 'Métodos de pagamento',
    'pricing_money_back'      => 'Garantia de devolução em 30 dias',
    'pricing_region_label'    => 'Região:',
    'pricing_change_region'   => 'Alterar',
    'pricing_no_fees_note'    => 'Sem cartão · Cancele quando quiser · Sem taxas de configuração',
    'pricing_feat_scheduling' => 'Agendamento inteligente de consultas',
    'pricing_feat_queue'      => 'Fila digital em tempo real',
    'pricing_feat_staff'      => 'Contas de funcionários ilimitadas',
    'pricing_feat_ratings'    => 'Avaliações e feedback de clientes',
    'pricing_feat_analytics'  => 'Análises e relatórios de negócio',
    'pricing_feat_reminders'  => 'Lembretes automáticos por SMS e e-mail',
    'pricing_feat_languages'  => '15 idiomas de interface',
    'pricing_feat_onboarding' => 'Assistente de integração',
    'pricing_feat_database'   => 'Base de dados isolada por inquilino',
    'pricing_feat_api'        => 'Acesso à API',
    'pricing_feat_booking'    => 'Página de reservas personalizada',
    'pricing_feat_support'    => 'Suporte prioritário',
    'pricing_after_trial'     => 'O que acontece depois do teste?',
    'trial_full_access'       => 'Acesso completo',
    'trial_full_days'         => 'Dias 1–:days',
    'trial_full_desc'         => 'Todas as funcionalidades desbloqueadas. Apenas e-mail. Sem cartão.',
    'trial_grace_title'       => 'Período de graça',
    'trial_grace_days'        => 'Dias :start–:end',
    'trial_grace_desc'        => '3 dias extra para escolher um plano antes das restrições.',
    'trial_readonly_title'    => 'Modo apenas leitura',
    'trial_readonly_day'      => 'Dia :day+',
    'trial_readonly_desc'     => 'Nada é eliminado. Faça upgrade a qualquer momento.',
    'stat_businesses'         => 'Empresas',
    'stat_appointments'       => 'Consultas',
    'stat_countries'          => 'Países',
    'registration_closed'     => 'Registros fechados de momento. Volte em breve.',
PHP;

/* ─────────────── RUSSIAN ─────────────── */
$translations['ru'] = <<<'PHP'

    // Pricing section — index page
    'pricing_one_plan'        => 'Один план — все функции — цена адаптируется к вашему региону.',
    'billing_save_months'     => 'Сэкономьте 2 месяца',
    'billing_billed'          => 'Списывается ',
    'pricing_platform'        => 'Полная платформа',
    'pricing_trial_badge'     => 'Бесплатный пробный период :days дней',
    'pricing_per_mo'          => '/мес',
    'pricing_no_card_trial'   => 'Банковская карта для пробного периода не нужна',
    'pricing_tax_badge'       => '— итого',
    'pricing_tax_note'        => 'будет добавлен при оплате. Итого:',
    'pricing_methods_heading' => 'Способы оплаты',
    'pricing_money_back'      => 'Гарантия возврата денег в течение 30 дней',
    'pricing_region_label'    => 'Регион:',
    'pricing_change_region'   => 'Изменить',
    'pricing_no_fees_note'    => 'Без карты · Отмена в любое время · Без платы за настройку',
    'pricing_feat_scheduling' => 'Умное планирование записей',
    'pricing_feat_queue'      => 'Цифровая очередь в реальном времени',
    'pricing_feat_staff'      => 'Неограниченное количество сотрудников',
    'pricing_feat_ratings'    => 'Отзывы и оценки клиентов',
    'pricing_feat_analytics'  => 'Аналитика и бизнес-отчёты',
    'pricing_feat_reminders'  => 'Автоматические SMS и email-напоминания',
    'pricing_feat_languages'  => '15 языков интерфейса',
    'pricing_feat_onboarding' => 'Мастер настройки',
    'pricing_feat_database'   => 'Изолированная база данных на клиента',
    'pricing_feat_api'        => 'Доступ к API',
    'pricing_feat_booking'    => 'Индивидуальная страница бронирования',
    'pricing_feat_support'    => 'Приоритетная поддержка',
    'pricing_after_trial'     => 'Что произойдёт после пробного периода?',
    'trial_full_access'       => 'Полный доступ',
    'trial_full_days'         => 'Дни 1–:days',
    'trial_full_desc'         => 'Все функции разблокированы. Только email. Карта не нужна.',
    'trial_grace_title'       => 'Льготный период',
    'trial_grace_days'        => 'Дни :start–:end',
    'trial_grace_desc'        => '3 дополнительных дня для выбора плана до начала ограничений.',
    'trial_readonly_title'    => 'Режим только для чтения',
    'trial_readonly_day'      => 'День :day+',
    'trial_readonly_desc'     => 'Данные не удаляются. Обновите план в любое время.',
    'stat_businesses'         => 'Компаний',
    'stat_appointments'       => 'Записей',
    'stat_countries'          => 'Стран',
    'registration_closed'     => 'Регистрация временно закрыта. Проверьте позже.',
PHP;

/* ─────────────── CHINESE ─────────────── */
$translations['zh'] = <<<'PHP'

    // Pricing section — index page
    'pricing_one_plan'        => '一个套餐 — 全部功能 — 价格因地区而异。',
    'billing_save_months'     => '节省2个月',
    'billing_billed'          => '按年计费 ',
    'pricing_platform'        => '完整平台',
    'pricing_trial_badge'     => ':days天免费试用',
    'pricing_per_mo'          => '/月',
    'pricing_no_card_trial'   => '免费试用无需信用卡',
    'pricing_tax_badge'       => '— 合计',
    'pricing_tax_note'        => '将在结账时添加。合计：',
    'pricing_methods_heading' => '支付方式',
    'pricing_money_back'      => '30天退款保证',
    'pricing_region_label'    => '地区：',
    'pricing_change_region'   => '更改',
    'pricing_no_fees_note'    => '无需信用卡 · 随时取消 · 无设置费用',
    'pricing_feat_scheduling' => '智能预约排班',
    'pricing_feat_queue'      => '实时数字排队',
    'pricing_feat_staff'      => '无限员工账户',
    'pricing_feat_ratings'    => '客户评分与反馈',
    'pricing_feat_analytics'  => '分析与业务报告',
    'pricing_feat_reminders'  => '自动短信和邮件提醒',
    'pricing_feat_languages'  => '15种界面语言',
    'pricing_feat_onboarding' => '引导设置向导',
    'pricing_feat_database'   => '每个租户独立数据库',
    'pricing_feat_api'        => 'API访问',
    'pricing_feat_booking'    => '自定义预订页面',
    'pricing_feat_support'    => '优先支持',
    'pricing_after_trial'     => '试用结束后会发生什么？',
    'trial_full_access'       => '完全访问',
    'trial_full_days'         => '第1–:days天',
    'trial_full_desc'         => '所有功能已解锁。仅需邮箱。无需信用卡。',
    'trial_grace_title'       => '宽限期',
    'trial_grace_days'        => '第:start–:end天',
    'trial_grace_desc'        => '额外3天选择套餐，超时才会启动限制。',
    'trial_readonly_title'    => '只读模式',
    'trial_readonly_day'      => '第:day+天',
    'trial_readonly_desc'     => '数据不会被删除。随时升级即可恢复完全访问。',
    'stat_businesses'         => '企业',
    'stat_appointments'       => '预约',
    'stat_countries'          => '国家',
    'registration_closed'     => '注册暂时关闭，请稍后再来。',
PHP;

/* ─────────────── JAPANESE ─────────────── */
$translations['ja'] = <<<'PHP'

    // Pricing section — index page
    'pricing_one_plan'        => '1つのプラン — 全機能込み — 価格は地域に合わせて変動。',
    'billing_save_months'     => '2ヶ月分お得',
    'billing_billed'          => '年払い ',
    'pricing_platform'        => 'フルプラットフォーム',
    'pricing_trial_badge'     => ':days日間無料トライアル',
    'pricing_per_mo'          => '/月',
    'pricing_no_card_trial'   => '無料トライアルにクレジットカード不要',
    'pricing_tax_badge'       => '— 合計',
    'pricing_tax_note'        => 'お支払い時に追加されます。合計：',
    'pricing_methods_heading' => 'お支払い方法',
    'pricing_money_back'      => '30日間返金保証',
    'pricing_region_label'    => '地域：',
    'pricing_change_region'   => '変更',
    'pricing_no_fees_note'    => 'カード不要 · いつでもキャンセル · 初期費用なし',
    'pricing_feat_scheduling' => 'スマート予約管理',
    'pricing_feat_queue'      => 'リアルタイムデジタル待ち行列',
    'pricing_feat_staff'      => '無制限スタッフアカウント',
    'pricing_feat_ratings'    => '顧客評価とフィードバック',
    'pricing_feat_analytics'  => '分析とビジネスレポート',
    'pricing_feat_reminders'  => 'SMS・メール自動リマインダー',
    'pricing_feat_languages'  => '15言語インターフェース',
    'pricing_feat_onboarding' => 'オンボーディングウィザード',
    'pricing_feat_database'   => 'テナントごとの独立DB',
    'pricing_feat_api'        => 'APIアクセス',
    'pricing_feat_booking'    => 'カスタム予約ページ',
    'pricing_feat_support'    => 'プライオリティサポート',
    'pricing_after_trial'     => 'トライアル終了後はどうなりますか？',
    'trial_full_access'       => 'フルアクセス',
    'trial_full_days'         => '1〜:days日目',
    'trial_full_desc'         => '全機能が利用可能。メールのみ。カード不要。',
    'trial_grace_title'       => '猶予期間',
    'trial_grace_days'        => ':start〜:end日目',
    'trial_grace_desc'        => '制限開始前にプランを選ぶための3日間。',
    'trial_readonly_title'    => '読み取り専用モード',
    'trial_readonly_day'      => ':day日目以降',
    'trial_readonly_desc'     => 'データは削除されません。いつでもアップグレード可能。',
    'stat_businesses'         => '企業',
    'stat_appointments'       => '予約件数',
    'stat_countries'          => 'カ国',
    'registration_closed'     => '現在登録を受け付けていません。後ほどご確認ください。',
PHP;

/* ─────────────── TURKISH ─────────────── */
$translations['tr'] = <<<'PHP'

    // Pricing section — index page
    'pricing_one_plan'        => 'Bir plan — tüm özellikler — fiyat bölgenize göre uyarlanır.',
    'billing_save_months'     => '2 ay tasarruf edin',
    'billing_billed'          => 'Yıllık faturalandırılır ',
    'pricing_platform'        => 'Tam Platform',
    'pricing_trial_badge'     => ':days günlük ücretsiz deneme',
    'pricing_per_mo'          => '/ay',
    'pricing_no_card_trial'   => 'Ücretsiz deneme için kredi kartı gerekmez',
    'pricing_tax_badge'       => '— toplam',
    'pricing_tax_note'        => 'ödeme sırasında eklenecektir. Toplam:',
    'pricing_methods_heading' => 'Ödeme yöntemleri',
    'pricing_money_back'      => '30 günlük para iade garantisi',
    'pricing_region_label'    => 'Bölge:',
    'pricing_change_region'   => 'Değiştir',
    'pricing_no_fees_note'    => 'Kart yok · İstediğinizde iptal edin · Kurulum ücreti yok',
    'pricing_feat_scheduling' => 'Akıllı randevu planlama',
    'pricing_feat_queue'      => 'Gerçek zamanlı dijital kuyruk',
    'pricing_feat_staff'      => 'Sınırsız personel hesabı',
    'pricing_feat_ratings'    => 'Müşteri puanları ve geri bildirimleri',
    'pricing_feat_analytics'  => 'Analitik ve iş raporları',
    'pricing_feat_reminders'  => 'Otomatik SMS ve e-posta hatırlatıcılar',
    'pricing_feat_languages'  => '15 arayüz dili',
    'pricing_feat_onboarding' => 'Kurulum sihirbazı',
    'pricing_feat_database'   => 'Her kiracı için izole veritabanı',
    'pricing_feat_api'        => 'API erişimi',
    'pricing_feat_booking'    => 'Özel rezervasyon sayfası',
    'pricing_feat_support'    => 'Öncelikli destek',
    'pricing_after_trial'     => 'Deneme süresinden sonra ne olur?',
    'trial_full_access'       => 'Tam Erişim',
    'trial_full_days'         => '1–:days. Günler',
    'trial_full_desc'         => 'Tüm özellikler aktif. Yalnızca e-posta. Kart gerekmez.',
    'trial_grace_title'       => 'Bekleme Süresi',
    'trial_grace_days'        => ':start–:end. Günler',
    'trial_grace_desc'        => 'Kısıtlamalar başlamadan önce plan seçmek için 3 ekstra gün.',
    'trial_readonly_title'    => 'Salt Okunur Mod',
    'trial_readonly_day'      => ':day. Gün ve sonrası',
    'trial_readonly_desc'     => 'Hiçbir şey silinmez. Tam erişimi geri yüklemek için istediğiniz zaman yükseltin.',
    'stat_businesses'         => 'İşletme',
    'stat_appointments'       => 'Randevu',
    'stat_countries'          => 'Ülke',
    'registration_closed'     => 'Kayıtlar şu an kapalı. Daha sonra tekrar deneyin.',
PHP;

/* ─────────────── HINDI ─────────────── */
$translations['hi'] = <<<'PHP'

    // Pricing section — index page
    'pricing_one_plan'        => 'एक प्लान — सभी सुविधाएं — कीमत आपके क्षेत्र के अनुसार बदलती है।',
    'billing_save_months'     => '2 महीने बचाएं',
    'billing_billed'          => 'वार्षिक बिलिंग ',
    'pricing_platform'        => 'पूर्ण प्लेटफ़ॉर्म',
    'pricing_trial_badge'     => ':days दिन का मुफ़्त ट्रायल',
    'pricing_per_mo'          => '/माह',
    'pricing_no_card_trial'   => 'मुफ़्त ट्रायल के लिए क्रेडिट कार्ड की ज़रूरत नहीं',
    'pricing_tax_badge'       => '— कुल',
    'pricing_tax_note'        => 'भुगतान के समय जोड़ा जाएगा। कुल:',
    'pricing_methods_heading' => 'भुगतान के तरीके',
    'pricing_money_back'      => '30 दिन की मनी-बैक गारंटी',
    'pricing_region_label'    => 'क्षेत्र:',
    'pricing_change_region'   => 'बदलें',
    'pricing_no_fees_note'    => 'कार्ड नहीं · कभी भी रद्द करें · कोई सेटअप शुल्क नहीं',
    'pricing_feat_scheduling' => 'स्मार्ट अपॉइंटमेंट शेड्यूलिंग',
    'pricing_feat_queue'      => 'रियल-टाइम डिजिटल कतार',
    'pricing_feat_staff'      => 'असीमित स्टाफ अकाउंट',
    'pricing_feat_ratings'    => 'ग्राहक रेटिंग और फीडबैक',
    'pricing_feat_analytics'  => 'एनालिटिक्स और बिज़नेस रिपोर्ट',
    'pricing_feat_reminders'  => 'स्वचालित SMS और ईमेल रिमाइंडर',
    'pricing_feat_languages'  => '15 इंटरफ़ेस भाषाएं',
    'pricing_feat_onboarding' => 'ऑनबोर्डिंग विज़ार्ड',
    'pricing_feat_database'   => 'प्रत्येक टेनेंट के लिए अलग डेटाबेस',
    'pricing_feat_api'        => 'API एक्सेस',
    'pricing_feat_booking'    => 'कस्टम बुकिंग पेज',
    'pricing_feat_support'    => 'प्राथमिकता सहायता',
    'pricing_after_trial'     => 'ट्रायल के बाद क्या होता है?',
    'trial_full_access'       => 'पूरा एक्सेस',
    'trial_full_days'         => 'दिन 1–:days',
    'trial_full_desc'         => 'सभी सुविधाएं अनलॉक। केवल ईमेल। कार्ड की ज़रूरत नहीं।',
    'trial_grace_title'       => 'छूट की अवधि',
    'trial_grace_days'        => 'दिन :start–:end',
    'trial_grace_desc'        => 'प्रतिबंध शुरू होने से पहले प्लान चुनने के लिए 3 अतिरिक्त दिन।',
    'trial_readonly_title'    => 'केवल पढ़ने का मोड',
    'trial_readonly_day'      => 'दिन :day+',
    'trial_readonly_desc'     => 'कुछ भी डिलीट नहीं होता। पूरा एक्सेस वापस पाने के लिए कभी भी अपग्रेड करें।',
    'stat_businesses'         => 'व्यवसाय',
    'stat_appointments'       => 'अपॉइंटमेंट',
    'stat_countries'          => 'देश',
    'registration_closed'     => 'पंजीकरण अभी बंद है। जल्द वापस आएं।',
PHP;

/* ─────────────── KOREAN ─────────────── */
$translations['ko'] = <<<'PHP'

    // Pricing section — index page
    'pricing_one_plan'        => '하나의 플랜 — 모든 기능 — 가격은 지역에 맞게 조정됩니다.',
    'billing_save_months'     => '2개월 절약',
    'billing_billed'          => '연간 청구 ',
    'pricing_platform'        => '전체 플랫폼',
    'pricing_trial_badge'     => ':days일 무료 체험',
    'pricing_per_mo'          => '/월',
    'pricing_no_card_trial'   => '무료 체험에 신용카드 불필요',
    'pricing_tax_badge'       => '— 합계',
    'pricing_tax_note'        => '결제 시 추가됩니다. 합계:',
    'pricing_methods_heading' => '결제 수단',
    'pricing_money_back'      => '30일 환불 보장',
    'pricing_region_label'    => '지역:',
    'pricing_change_region'   => '변경',
    'pricing_no_fees_note'    => '카드 불필요 · 언제든 취소 · 설정 비용 없음',
    'pricing_feat_scheduling' => '스마트 예약 스케줄링',
    'pricing_feat_queue'      => '실시간 디지털 대기열',
    'pricing_feat_staff'      => '무제한 직원 계정',
    'pricing_feat_ratings'    => '고객 평점 및 피드백',
    'pricing_feat_analytics'  => '분석 및 비즈니스 리포트',
    'pricing_feat_reminders'  => '자동 SMS 및 이메일 알림',
    'pricing_feat_languages'  => '15가지 인터페이스 언어',
    'pricing_feat_onboarding' => '온보딩 마법사',
    'pricing_feat_database'   => '테넌트별 독립 데이터베이스',
    'pricing_feat_api'        => 'API 접근',
    'pricing_feat_booking'    => '맞춤형 예약 페이지',
    'pricing_feat_support'    => '우선 지원',
    'pricing_after_trial'     => '체험 후 어떻게 되나요?',
    'trial_full_access'       => '전체 접근',
    'trial_full_days'         => '1–:days일',
    'trial_full_desc'         => '모든 기능 잠금 해제. 이메일만 필요. 카드 불필요.',
    'trial_grace_title'       => '유예 기간',
    'trial_grace_days'        => ':start–:end일',
    'trial_grace_desc'        => '제한 시작 전 플랜을 선택할 수 있는 3일 추가.',
    'trial_readonly_title'    => '읽기 전용 모드',
    'trial_readonly_day'      => ':day일+',
    'trial_readonly_desc'     => '아무것도 삭제되지 않습니다. 언제든 업그레이드하여 복원하세요.',
    'stat_businesses'         => '기업',
    'stat_appointments'       => '예약',
    'stat_countries'          => '국가',
    'registration_closed'     => '현재 등록이 마감되었습니다. 나중에 다시 확인하세요.',
PHP;

/* ─────────────── DUTCH ─────────────── */
$translations['nl'] = <<<'PHP'

    // Pricing section — index page
    'pricing_one_plan'        => 'Één plan — alle functies — prijs past zich aan uw regio aan.',
    'billing_save_months'     => 'Bespaar 2 maanden',
    'billing_billed'          => 'Jaarlijks gefactureerd ',
    'pricing_platform'        => 'Volledig platform',
    'pricing_trial_badge'     => ':days dagen gratis proberen',
    'pricing_per_mo'          => '/mnd',
    'pricing_no_card_trial'   => 'Geen creditcard nodig voor de gratis proefperiode',
    'pricing_tax_badge'       => '— totaal',
    'pricing_tax_note'        => 'wordt toegevoegd bij betaling. Totaal:',
    'pricing_methods_heading' => 'Betaalmethoden',
    'pricing_money_back'      => '30 dagen geld-terug-garantie',
    'pricing_region_label'    => 'Regio:',
    'pricing_change_region'   => 'Wijzigen',
    'pricing_no_fees_note'    => 'Geen kaart · Annuleer wanneer u wilt · Geen installatiekosten',
    'pricing_feat_scheduling' => 'Slimme afspraakplanning',
    'pricing_feat_queue'      => 'Realtime digitale wachtrij',
    'pricing_feat_staff'      => 'Onbeperkte personeelsaccounts',
    'pricing_feat_ratings'    => 'Klantbeoordelingen en feedback',
    'pricing_feat_analytics'  => 'Analyses en bedrijfsrapporten',
    'pricing_feat_reminders'  => 'Geautomatiseerde sms- en e-mailherinneringen',
    'pricing_feat_languages'  => '15 interfacetalen',
    'pricing_feat_onboarding' => 'Onboarding-wizard',
    'pricing_feat_database'   => 'Geïsoleerde database per huurder',
    'pricing_feat_api'        => 'API-toegang',
    'pricing_feat_booking'    => 'Aangepaste boekingspagina',
    'pricing_feat_support'    => 'Prioriteitsondersteuning',
    'pricing_after_trial'     => 'Wat gebeurt er na de proefperiode?',
    'trial_full_access'       => 'Volledige toegang',
    'trial_full_days'         => 'Dagen 1–:days',
    'trial_full_desc'         => 'Alle functies ontgrendeld. Alleen e-mail. Geen kaart nodig.',
    'trial_grace_title'       => 'Respijtperiode',
    'trial_grace_days'        => 'Dagen :start–:end',
    'trial_grace_desc'        => '3 extra dagen om een plan te kiezen voordat beperkingen ingaan.',
    'trial_readonly_title'    => 'Alleen-lezenmodus',
    'trial_readonly_day'      => 'Dag :day+',
    'trial_readonly_desc'     => 'Er wordt niets verwijderd. Upgrade op elk moment om volledige toegang te herstellen.',
    'stat_businesses'         => 'Bedrijven',
    'stat_appointments'       => 'Afspraken',
    'stat_countries'          => 'Landen',
    'registration_closed'     => 'Registratie is momenteel gesloten. Kom later terug.',
PHP;

/* ─────────────── INDONESIAN ─────────────── */
$translations['id'] = <<<'PHP'

    // Pricing section — index page
    'pricing_one_plan'        => 'Satu paket — semua fitur — harga disesuaikan dengan wilayah Anda.',
    'billing_save_months'     => 'Hemat 2 bulan',
    'billing_billed'          => 'Ditagih tahunan ',
    'pricing_platform'        => 'Platform lengkap',
    'pricing_trial_badge'     => 'Coba gratis :days hari',
    'pricing_per_mo'          => '/bln',
    'pricing_no_card_trial'   => 'Tidak perlu kartu kredit untuk uji coba gratis',
    'pricing_tax_badge'       => '— total',
    'pricing_tax_note'        => 'akan ditambahkan saat pembayaran. Total:',
    'pricing_methods_heading' => 'Metode pembayaran',
    'pricing_money_back'      => 'Garansi uang kembali 30 hari',
    'pricing_region_label'    => 'Wilayah:',
    'pricing_change_region'   => 'Ubah',
    'pricing_no_fees_note'    => 'Tanpa kartu · Batalkan kapan saja · Tanpa biaya pengaturan',
    'pricing_feat_scheduling' => 'Penjadwalan janji temu cerdas',
    'pricing_feat_queue'      => 'Antrian digital real-time',
    'pricing_feat_staff'      => 'Akun staf tak terbatas',
    'pricing_feat_ratings'    => 'Penilaian dan umpan balik pelanggan',
    'pricing_feat_analytics'  => 'Analitik dan laporan bisnis',
    'pricing_feat_reminders'  => 'Pengingat SMS dan email otomatis',
    'pricing_feat_languages'  => '15 bahasa antarmuka',
    'pricing_feat_onboarding' => 'Panduan orientasi',
    'pricing_feat_database'   => 'Database terisolasi per penyewa',
    'pricing_feat_api'        => 'Akses API',
    'pricing_feat_booking'    => 'Halaman pemesanan kustom',
    'pricing_feat_support'    => 'Dukungan prioritas',
    'pricing_after_trial'     => 'Apa yang terjadi setelah masa uji coba?',
    'trial_full_access'       => 'Akses penuh',
    'trial_full_days'         => 'Hari 1–:days',
    'trial_full_desc'         => 'Semua fitur terbuka. Email saja. Tidak perlu kartu.',
    'trial_grace_title'       => 'Periode tenggang',
    'trial_grace_days'        => 'Hari :start–:end',
    'trial_grace_desc'        => '3 hari ekstra untuk memilih paket sebelum pembatasan berlaku.',
    'trial_readonly_title'    => 'Mode hanya baca',
    'trial_readonly_day'      => 'Hari :day+',
    'trial_readonly_desc'     => 'Tidak ada yang dihapus. Tingkatkan kapan saja untuk memulihkan akses penuh.',
    'stat_businesses'         => 'Bisnis',
    'stat_appointments'       => 'Janji temu',
    'stat_countries'          => 'Negara',
    'registration_closed'     => 'Pendaftaran saat ini ditutup. Cek kembali nanti.',
PHP;

// ─── Apply to each file ───────────────────────────────────────────────────────
$errors = [];
foreach ($translations as $lang => $block) {
    $file = "$base/$lang/landing.php";

    if (!file_exists($file)) {
        $errors[] = "MISSING: $file";
        continue;
    }

    $content = file_get_contents($file);

    // Check key doesn't already exist (idempotency guard)
    if (strpos($content, "'pricing_one_plan'") !== false) {
        echo "SKIP (already present): $lang\n";
        continue;
    }

    // Find last ];  and insert new block before it
    $pos = strrpos($content, '];');
    if ($pos === false) {
        $errors[] = "NO CLOSING ]: $file";
        continue;
    }

    $newContent = substr($content, 0, $pos) . $block . "\n];\n";
    file_put_contents($file, $newContent);
    echo "OK: $lang\n";
}

if ($errors) {
    echo "\nERRORS:\n";
    foreach ($errors as $e) echo "  $e\n";
} else {
    echo "\nAll done!\n";
}
