<?php
return [
 'appointment_booked'=>['subject'=>'Afspraakbevestiging','greeting'=>'Hallo :name,','message'=>'Uw afspraak is succesvol geboekt!','details'=>'Afspraakgegevens:','date'=>'Datum: :date','time'=>'Tijd: :time','tenant'=>'Kliniek: :tenant','footer'=>'Bedankt voor het gebruik van onze diensten!','sms'=>'Hallo :name, uw afspraak is op :date om :time bij :tenant'],
 'appointment_reminder'=>['subject'=>'Afspraakherinnering','greeting'=>'Hallo :name,','message'=>'Dit is een herinnering voor uw komende afspraak!','details'=>'Afspraakgegevens:','date'=>'Datum: :date','time'=>'Tijd: :time','tenant'=>'Kliniek: :tenant','footer'=>'We kijken ernaar uit u te zien!','sms'=>'Herinnering: uw afspraak is op :date om :time bij :tenant'],
 'appointment_cancelled'=>['subject'=>'Afspraak geannuleerd','greeting'=>'Hallo :name,','message'=>'Uw afspraak is geannuleerd.','details'=>'Gegevens van de geannuleerde afspraak:','date'=>'Datum: :date','time'=>'Tijd: :time','tenant'=>'Kliniek: :tenant','footer'=>'U kunt altijd een nieuwe afspraak maken.','sms'=>'Uw afspraak op :date om :time bij :tenant is geannuleerd'],
 'appointment_confirmed'=>['subject'=>'Afspraak bevestigd','greeting'=>'Hallo :name,','message'=>'Uw afspraak is bevestigd!','details'=>'Afspraakgegevens:','date'=>'Datum: :date','time'=>'Tijd: :time','tenant'=>'Kliniek: :tenant','footer'=>'We kijken ernaar uit u te zien!','sms'=>'Uw afspraak op :date om :time bij :tenant is bevestigd'],
 'queue_next'=>['subject'=>'U bent aan de beurt!','greeting'=>'Hallo :name,','message'=>'U bent aan de beurt! Ga nu naar de balie.','queue_number'=>'Wachtnummer: :number','footer'=>'Bedankt voor het wachten!','sms'=>'Hallo :name, u bent aan de beurt! Nummer: :number. Ga naar de balie.'],
 'queue_position_update'=>['subject'=>'Update van uw wachtrijpositie','greeting'=>'Hallo :name,','message'=>'Update van uw positie in de wachtrij:','queue_number'=>'Wachtnummer: :number','position'=>'Personen voor u: :position','estimated_wait'=>'Geschatte wachttijd: :time minuten','footer'=>'Bedankt voor uw geduld!','sms'=>'Nummer: :number, :position personen voor u, geschatte tijd: :time minuten'],
 'queue_ready'=>['subject'=>'Bijna aan de beurt','greeting'=>'Hallo :name,','message'=>'Maak u klaar, u bent bijna aan de beurt!','queue_number'=>'Wachtnummer: :number','position'=>'Er is nog 1 persoon voor u','footer'=>'Bedankt voor het wachten!','sms'=>'Maak u klaar! Nummer: :number, nog 1 persoon voor u.'],
 'queue_skipped'=>['subject'=>'Uw beurt is overgeslagen','greeting'=>'Hallo :name,','message'=>'Uw beurt is overgeslagen omdat u afwezig was.','queue_number'=>'Wachtnummer: :number','footer'=>'U kunt bij de balie een nieuw nummer krijgen.','sms'=>'Uw beurt (nummer :number) is overgeslagen wegens afwezigheid. U kunt een nieuw nummer krijgen.'],
 'view_details'=>'Details bekijken','thank_you'=>'Bedankt voor het gebruik van onze diensten','regards'=>'Met vriendelijke groet',
];
