<?php

use App\Http\Controllers\Auth\SuperAdminAuthController;
use App\Http\Controllers\Auth\TenantRegistrationController;
use App\Http\Controllers\CountrySettingController;
use App\Http\Controllers\LandingController;
use App\Http\Controllers\PlanPriceController;
use App\Http\Controllers\PricingController;
use App\Http\Controllers\SuperAdmin\CountryPricingController;
use App\Http\Controllers\SuperAdmin\PromoCodeController;
use App\Http\Controllers\SuperAdminController;
use App\Http\Middleware\SetCentralLocale;
use App\Services\PricingService;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes - Central Domain Only
|--------------------------------------------------------------------------
| velora.com  → Landing Page + Signup
| admin.velora.com → Super Admin (handled via prefix below)
| *.velora.com → Tenant routes (routes/tenant.php)
*/

// ── Stripe Webhook (no CSRF, no middleware) ──────────────────────────────
Route::post('/webhooks/stripe', [\App\Http\Controllers\StripeWebhookController::class, 'handle'])
    ->withoutMiddleware([\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken::class])
    ->name('webhooks.stripe');

// ── Moyasar Webhook (no CSRF, no middleware) ─────────────────────────────
Route::post('/webhooks/moyasar', [\App\Http\Controllers\MoyasarWebhookController::class, 'handle'])
    ->withoutMiddleware([\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken::class])
    ->name('webhooks.moyasar');

// ── Landing + Marketing Routes ───────────────────────────────────────────────
// Laravel Localizer owns locale resolution for these pages. The default locale
// (Arabic) is unprefixed; every other locale receives a /{locale} prefix.
Route::middleware(['web', 'maintenance'])
    ->domain(env('APP_DOMAIN', 'velora.test'))
    ->group(function () {
        try {
            \Illuminate\Support\Facades\URL::defaults(['tenantSubdomain' => 'demo']);
        } catch (\Throwable $_) {
        }

        Route::localize(function () {
            Route::get('/', function (\Illuminate\Http\Request $request) {
                try {
                    $controller = app()->make(\App\Http\Controllers\LandingController::class);
                    return $controller->index($request);
                } catch (\Throwable $e) {
                    \Illuminate\Support\Facades\Log::error('Landing render failed: ' . $e->getMessage());
                    try {
                        \Illuminate\Support\Facades\URL::defaults(['tenantSubdomain' => 'demo']);
                    } catch (\Throwable $_) {
                    }
                    return response('Velora landing temporarily unavailable (fallback)', 200);
                }
            })->name('landing');

            Route::get('/pricing', [LandingController::class, 'pricing'])->name('pricing');

            Route::post('/pricing/set-country', [PricingController::class, 'setCountry'])
                ->name('pricing.set-country')
                ->middleware('throttle:30,1');

            Route::get('/signup', [LandingController::class, 'signup'])->name('signup');

            Route::get('/signup/check-subdomain', [LandingController::class, 'checkSubdomain'])
                ->name('signup.check-subdomain')
                ->middleware('throttle:60,1');

            Route::post('/signup', [TenantRegistrationController::class, 'store'])
                ->name('signup.store')
                ->middleware('throttle:10,1');

            Route::get('/login', function () {
                return view('landing.find-account', [
                    'baseDomain' => config('app.base_domain', 'velora.com'),
                ]);
            })->name('central.login');
        });

        // Keep the legacy endpoint temporarily for existing bookmarks/clients.
        // New UI uses the localized route generated by Laravel Localizer.
        Route::get('/lang/{locale}', function ($locale) {
            $supported = config('localizer.supported_locales', []);
            if (! in_array($locale, $supported, true)) {
                abort(404);
            }

            return redirect()->to('/' . $locale);
        })->whereIn('locale', config('localizer.supported_locales', []))
            ->name('landing.lang');

        Route::get('/region/{locale}/{country}', function ($locale, $country) {
            $supported = config('localizer.supported_locales', []);
            $locale = in_array($locale, $supported, true) ? $locale : config('localizer.supported_locales.0', 'ar');
            $code = strtoupper(preg_replace('/[^A-Za-z]/', '', $country));
            if (strlen($code) < 2 || strlen($code) > 10) {
                return redirect()->route('landing');
            }
            session(['pricing_country_override' => $code]);

            return redirect()->to('/' . $locale)
                ->withCookie(cookie()->forever('velora_country_override', $code));
        })->whereIn('locale', config('localizer.supported_locales', []))
            ->name('landing.region');

        Route::get('/currency/{currency}', function ($currency) {
            $currency = strtoupper($currency);
            if (strlen($currency) === 3 && ctype_alpha($currency)) {
                session()->put('current_currency', $currency);
                cookie()->queue(cookie()->forever('velora_currency_override', $currency));
            }
            return redirect()->back();
        })->name('landing.currency');
    });

// Super Admin Routes (Central - No Tenant)
Route::prefix('super-admin')
    ->name('super-admin.')
    ->middleware([
        'web',
        SetCentralLocale::class,
    ])
    ->group(function () {
        Route::get('/login', function () {
            if (auth()->guard('web')->check() && auth()->guard('web')->user()->isSuperAdmin()) {
                return redirect()->route('super-admin.dashboard');
            }
            return view('super-admin.login');
        })->name('login');

        Route::post('/login', [SuperAdminAuthController::class, 'webLogin'])->name('login.post');
        Route::post('/logout', [SuperAdminAuthController::class, 'webLogout'])->name('logout');

        Route::get('/lang/{locale}', function ($locale) {
            $supported = ['en', 'ar'];
            if (in_array($locale, $supported, true)) {
                session()->put('central_locale', $locale);
            }
            return redirect()->back();
        })->name('lang');

        Route::middleware(['super.admin.auth'])->group(function () {
            Route::get('/dashboard', [SuperAdminController::class, 'dashboard'])->name('dashboard');

            Route::get('/tenants', function () {
                return view('super-admin.tenants');
            })->name('tenants');

            Route::get('/subscription-plans', function () {
                return view('super-admin.subscription-plans');
            })->name('subscription-plans');

            Route::get('/activity-logs', function () {
                $logs = \App\Models\ActivityLog::with('user:id,name')
                    ->latest()
                    ->paginate(5);

                $meta = [
                    'current_page'  => $logs->currentPage(),
                    'last_page'     => $logs->lastPage(),
                    'from'          => $logs->firstItem() ?? 0,
                    'to'            => $logs->lastItem() ?? 0,
                    'total'         => $logs->total(),
                    'prev_page_url' => $logs->previousPageUrl(),
                    'next_page_url' => $logs->nextPageUrl(),
                ];

                $stats = [
                    'today'      => \App\Models\ActivityLog::whereDate('created_at', today())->count(),
                    'this_week'  => \App\Models\ActivityLog::whereBetween('created_at', [now()->startOfWeek(), now()->endOfWeek()])->count(),
                    'this_month' => \App\Models\ActivityLog::whereMonth('created_at', now()->month)->count(),
                ];

                return view('super-admin.activity-logs', compact('logs', 'meta', 'stats'));
            })->name('activity-logs');

            Route::get('/settings', function () {
                return view('super-admin.settings');
            })->name('settings');

            Route::get('/notifications', function () {
                return view('super-admin.notifications');
            })->name('notifications');

            Route::get('/analytics', function () {
                return view('super-admin.analytics');
            })->name('analytics');

            Route::get('/reports', function () {
                return redirect()->route('super-admin.analytics', ['tab' => 'reports']);
            })->name('reports');

            Route::get('/kpis', function () {
                return redirect()->route('super-admin.analytics', ['tab' => 'kpis']);
            })->name('kpis');

            Route::get('/kpis/export.csv', [\App\Http\Controllers\SuperAdmin\DashboardController::class, 'exportKpis'])->name('kpis.export');

            Route::get('/upgrade-requests', [SuperAdminController::class, 'upgradeRequests'])->name('upgrade-requests');
            Route::get('/upgrade-requests/{id}', [SuperAdminController::class, 'showUpgradeRequest'])->name('upgrade-requests.show');
            Route::post('/upgrade-requests/{id}/approve', [SuperAdminController::class, 'approveUpgrade'])->name('upgrade-requests.approve');
            Route::post('/upgrade-requests/{id}/reject', [SuperAdminController::class, 'rejectUpgrade'])->name('upgrade-requests.reject');

            Route::resource('countries', CountrySettingController::class);

            Route::get('/subscription-plans/{plan}/prices', [PlanPriceController::class, 'index'])
                ->name('plan-prices.index');
            Route::post('/subscription-plans/{plan}/prices', [PlanPriceController::class, 'store'])
                ->name('plan-prices.store');
            Route::put('/subscription-plans/{plan}/prices/{planPrice}', [PlanPriceController::class, 'update'])
                ->name('plan-prices.update');
            Route::delete('/subscription-plans/{plan}/prices/{planPrice}', [PlanPriceController::class, 'destroy'])
                ->name('plan-prices.destroy');

            Route::resource('country-pricing', CountryPricingController::class)
                ->names('country-pricing');
            Route::post('country-pricing/{countryPricing}/toggle', [CountryPricingController::class, 'toggleActive'])
                ->name('country-pricing.toggle');

            Route::get('/promo-codes', [PromoCodeController::class, 'index'])->name('promo-codes.index');
            Route::post('/promo-codes', [PromoCodeController::class, 'store'])->name('promo-codes.store');
            Route::patch('/promo-codes/{id}/toggle', [PromoCodeController::class, 'toggle'])->name('promo-codes.toggle');
            Route::delete('/promo-codes/{id}', [PromoCodeController::class, 'destroy'])->name('promo-codes.destroy');
        });
    });
