<?php
return [
    'appointment_booked'=>['subject'=>'Konfirmasi Janji Temu','greeting'=>'Halo :name,','message'=>'Janji temu Anda berhasil dibuat!','details'=>'Detail janji temu:','date'=>'Tanggal: :date','time'=>'Waktu: :time','tenant'=>'Klinik: :tenant','footer'=>'Terima kasih telah menggunakan layanan kami!','sms'=>'Halo :name, janji temu Anda pada :date pukul :time di :tenant'],
    'appointment_reminder'=>['subject'=>'Pengingat Janji Temu','greeting'=>'Halo :name,','message'=>'Ini pengingat untuk janji temu Anda berikutnya!','details'=>'Detail janji temu:','date'=>'Tanggal: :date','time'=>'Waktu: :time','tenant'=>'Klinik: :tenant','footer'=>'Kami menantikan kedatangan Anda!','sms'=>'Pengingat: janji temu Anda pada :date pukul :time di :tenant'],
    'appointment_cancelled'=>['subject'=>'Janji Temu Dibatalkan','greeting'=>'Halo :name,','message'=>'Janji temu Anda telah dibatalkan.','details'=>'Detail janji temu yang dibatalkan:','date'=>'Tanggal: :date','time'=>'Waktu: :time','tenant'=>'Klinik: :tenant','footer'=>'Anda dapat membuat janji temu lain kapan saja.','sms'=>'Janji temu Anda pada :date pukul :time di :tenant telah dibatalkan'],
    'appointment_confirmed'=>['subject'=>'Janji Temu Dikonfirmasi','greeting'=>'Halo :name,','message'=>'Janji temu Anda telah dikonfirmasi!','details'=>'Detail janji temu:','date'=>'Tanggal: :date','time'=>'Waktu: :time','tenant'=>'Klinik: :tenant','footer'=>'Kami menantikan kedatangan Anda!','sms'=>'Janji temu Anda pada :date pukul :time di :tenant telah dikonfirmasi'],
    'queue_next'=>['subject'=>'Sekarang Giliran Anda!','greeting'=>'Halo :name,','message'=>'Sekarang giliran Anda! Silakan menuju meja layanan.','queue_number'=>'Nomor antrean: :number','footer'=>'Terima kasih telah menunggu!','sms'=>'Halo :name, sekarang giliran Anda! Nomor antrean: :number. Silakan menuju meja layanan.'],
    'queue_position_update'=>['subject'=>'Pembaruan Posisi Antrean','greeting'=>'Halo :name,','message'=>'Pembaruan posisi antrean Anda:','queue_number'=>'Nomor antrean: :number','position'=>'Orang di depan Anda: :position','estimated_wait'=>'Perkiraan waktu tunggu: :time menit','footer'=>'Terima kasih atas kesabaran Anda!','sms'=>'Nomor antrean: :number, :position orang di depan, perkiraan waktu: :time menit'],
    'queue_ready'=>['subject'=>'Hampir Giliran Anda','greeting'=>'Halo :name,','message'=>'Bersiaplah, giliran Anda akan segera tiba!','queue_number'=>'Nomor antrean: :number','position'=>'Hanya 1 orang di depan Anda','footer'=>'Terima kasih telah menunggu!','sms'=>'Bersiaplah! Nomor antrean: :number, hanya 1 orang di depan Anda.'],
    'queue_skipped'=>['subject'=>'Giliran Anda Dilewati','greeting'=>'Halo :name,','message'=>'Giliran Anda dilewati karena tidak hadir.','queue_number'=>'Nomor antrean: :number','footer'=>'Anda dapat mengambil nomor antrean baru di meja layanan.','sms'=>'Giliran Anda (nomor :number) dilewati karena tidak hadir. Anda dapat mengambil nomor antrean baru.'],
    'view_details'=>'Lihat Detail','thank_you'=>'Terima kasih telah menggunakan layanan kami','regards'=>'Salam',
];
