<?php
return [
 'appointment_booked'=>['subject'=>'Conferma appuntamento','greeting'=>'Ciao :name,','message'=>'Il tuo appuntamento è stato prenotato con successo!','details'=>'Dettagli appuntamento:','date'=>'Data: :date','time'=>'Ora: :time','tenant'=>'Clinica: :tenant','footer'=>'Grazie per aver utilizzato i nostri servizi!','sms'=>'Ciao :name, il tuo appuntamento è il :date alle :time presso :tenant'],
 'appointment_reminder'=>['subject'=>'Promemoria appuntamento','greeting'=>'Ciao :name,','message'=>'Questo è un promemoria per il tuo prossimo appuntamento!','details'=>'Dettagli appuntamento:','date'=>'Data: :date','time'=>'Ora: :time','tenant'=>'Clinica: :tenant','footer'=>'Non vediamo l’ora di vederti!','sms'=>'Promemoria: appuntamento il :date alle :time presso :tenant'],
 'appointment_cancelled'=>['subject'=>'Appuntamento annullato','greeting'=>'Ciao :name,','message'=>'Il tuo appuntamento è stato annullato.','details'=>'Dettagli appuntamento annullato:','date'=>'Data: :date','time'=>'Ora: :time','tenant'=>'Clinica: :tenant','footer'=>'Puoi prenotare un altro appuntamento in qualsiasi momento.','sms'=>'Il tuo appuntamento del :date alle :time presso :tenant è stato annullato'],
 'appointment_confirmed'=>['subject'=>'Appuntamento confermato','greeting'=>'Ciao :name,','message'=>'Il tuo appuntamento è stato confermato!','details'=>'Dettagli appuntamento:','date'=>'Data: :date','time'=>'Ora: :time','tenant'=>'Clinica: :tenant','footer'=>'Non vediamo l’ora di vederti!','sms'=>'Il tuo appuntamento del :date alle :time presso :tenant è confermato'],
 'queue_next'=>['subject'=>'È il tuo turno!','greeting'=>'Ciao :name,','message'=>'È il tuo turno! Vai ora allo sportello.','queue_number'=>'Numero coda: :number','footer'=>'Grazie per l’attesa!','sms'=>'Ciao :name, è il tuo turno! Numero coda: :number. Vai allo sportello.'],
 'queue_position_update'=>['subject'=>'Aggiornamento posizione in coda','greeting'=>'Ciao :name,','message'=>'Aggiornamento della tua posizione in coda:','queue_number'=>'Numero coda: :number','position'=>'Persone davanti a te: :position','estimated_wait'=>'Tempo di attesa stimato: :time minuti','footer'=>'Grazie per la pazienza!','sms'=>'Numero coda: :number, :position persone davanti, tempo stimato: :time minuti'],
 'queue_ready'=>['subject'=>'Quasi il tuo turno','greeting'=>'Ciao :name,','message'=>'Preparati, il tuo turno arriverà molto presto!','queue_number'=>'Numero coda: :number','position'=>'Solo 1 persona davanti a te','footer'=>'Grazie per l’attesa!','sms'=>'Preparati! Numero coda: :number, solo 1 persona davanti a te.'],
 'queue_skipped'=>['subject'=>'Il tuo turno è stato saltato','greeting'=>'Ciao :name,','message'=>'Il tuo turno è stato saltato per assenza.','queue_number'=>'Numero coda: :number','footer'=>'Puoi prendere un nuovo numero allo sportello.','sms'=>'Il tuo turno (numero :number) è stato saltato per assenza. Puoi prendere un nuovo numero.'],
 'view_details'=>'Vedi dettagli','thank_you'=>'Grazie per aver utilizzato i nostri servizi','regards'=>'Cordiali saluti',
];
