<?php

$base = require __DIR__ . '/../en/landing.php';

return array_replace($base, [
    'hero_badge' => 'Precios para prueba de :days días', 'hero_headline_1' => 'Gestión inteligente de citas y colas', 'hero_headline_2' => 'para', 'hero_headline_hl' => 'pequeñas empresas', 'hero_sub' => 'Simplifica las citas, reduce las esperas y satisface a tus clientes.', 'hero_cta_start' => 'Iniciar prueba gratis (:days días)', 'hero_cta_how' => 'Cómo funciona',
    'trust_no_card' => 'Sin tarjeta de crédito', 'trust_setup' => 'Configuración fácil', 'trust_cancel' => 'Cancela cuando quieras', 'trust_languages' => 'Soporte multilingüe',
    'ticker_scheduling' => 'Programación', 'ticker_queue' => 'Funciones de cola', 'ticker_uptime' => '99,9 % de disponibilidad', 'trusted_countries' => 'De confianza en varios países',
    'features_badge' => 'Funciones', 'features_title' => 'Todo lo que necesitas para', 'features_title_hl' => 'gestionar citas', 'features_sub' => 'Herramientas para programación, colas, recordatorios e informes',
    'f1_title' => 'Reservas', 'f1_desc' => 'Reservas online mediante web y enlaces.', 'f1_tag' => 'Reservas', 'f2_title' => 'Programación', 'f2_desc' => 'Horarios flexibles y franjas para el personal.', 'f2_tag' => 'Programación', 'f3_title' => 'Clientes', 'f3_desc' => 'Gestiona perfiles e historial de clientes.', 'f3_tag' => 'CRM', 'f4_title' => 'Informes', 'f4_desc' => 'Información sobre citas y personal.', 'f4_tag' => 'Analítica', 'f5_title' => 'Multi-región', 'f5_desc' => 'Soporte para varios países e idiomas.', 'f5_tag' => 'Global', 'f6_title' => 'Notificaciones', 'f6_desc' => 'Recordatorios por correo y SMS.', 'f6_tag' => 'Recordatorios', 'f7_title' => 'Valoraciones', 'f7_desc' => 'Recoge comentarios de los clientes.', 'f7_tag' => 'Opiniones', 'f8_title' => 'Seguridad', 'f8_desc' => 'Protección de datos y copias de seguridad.', 'f8_tag' => 'Seguro', 'f9_title' => 'Rápido', 'f9_desc' => 'Alto rendimiento y disponibilidad.', 'f9_tag' => 'Velocidad',
    'how_badge' => 'Cómo funciona', 'how_title' => 'Configura y', 'how_title_hl' => 'empieza a aceptar citas', 'how_sub' => 'Tres pasos sencillos para empezar.', 's1_title' => 'Crea tu cuenta', 's1_desc' => 'Regístrate y configura los datos de tu negocio.', 's2_title' => 'Añade personal y servicios', 's2_desc' => 'Define personal, servicios y horarios disponibles.', 's3_title' => 'Acepta reservas', 's3_desc' => 'Comparte enlaces de reserva y gestiona las colas.', 'how_cta' => 'Empezar',
    'pricing_badge' => 'Precios', 'pricing_title' => 'Precios simples para', 'pricing_title_hl' => 'equipos en crecimiento', 'pricing_one_plan' => 'Un plan para la mayoría de los negocios', 'billing_monthly' => 'Mensual', 'billing_yearly' => 'Anual', 'pricing_platform' => 'Plataforma', 'pricing_trial_badge' => 'Prueba gratis de :days días', 'pricing_per_mo' => 'al mes', 'pricing_per_year' => 'al año', 'pricing_no_card_trial' => 'No se requiere tarjeta para la prueba', 'pricing_start_trial' => 'Iniciar prueba gratis (:days días)', 'pricing_no_fees_note' => 'Sin cargos ocultos durante la prueba', 'registration_closed' => 'El registro está cerrado actualmente', 'pricing_methods_heading' => 'Métodos de pago', 'pricing_tax_badge' => 'Se aplican impuestos', 'pricing_tax_note' => 'Impuestos aplicados al precio mensual', 'pricing_money_back' => 'Garantía de devolución de 30 días', 'pricing_region_label' => 'Región', 'pricing_change_region' => 'Cambiar región', 'whats_included' => 'Qué incluye', 'pricing_feat_scheduling' => 'Programación', 'pricing_feat_queue' => 'Gestión de colas', 'pricing_feat_staff' => 'Gestión del personal', 'pricing_feat_ratings' => 'Valoraciones y reseñas', 'pricing_feat_analytics' => 'Analítica', 'pricing_feat_reminders' => 'Recordatorios', 'pricing_feat_languages' => 'Idiomas', 'pricing_feat_onboarding' => 'Configuración inicial', 'pricing_feat_database' => 'Copias de seguridad', 'pricing_feat_api' => 'Acceso API', 'pricing_feat_booking' => 'Enlaces de reserva', 'pricing_feat_support' => 'Soporte por correo',
    'stat_businesses' => 'Negocios que usan la plataforma', 'stat_appointments' => 'Citas reservadas', 'stat_countries' => 'Países compatibles', 'testimonials_badge' => 'Opiniones', 'testimonials_title' => 'Lo que dicen', 'testimonials_hl' => 'nuestros clientes', 'faq_badge' => 'Preguntas frecuentes', 'faq_title' => 'Preguntas', 'faq_title_hl' => 'frecuentes', 'faq_1_q' => '¿Cómo funciona la prueba?', 'faq_1_a' => 'Obtienes acceso completo durante el periodo de prueba.', 'faq_2_q' => '¿Admiten varios idiomas?', 'faq_2_a' => 'Sí, la plataforma admite varios idiomas.', 'faq_3_q' => '¿Puedo cancelar en cualquier momento?', 'faq_3_a' => 'Sí, puedes cancelar desde la configuración de tu cuenta.', 'faq_4_q' => '¿Ofrecen reembolsos?', 'faq_4_a' => 'Ofrecemos una garantía de devolución de 30 días.', 'faq_5_q' => '¿Mis datos están seguros?', 'faq_5_a' => 'Seguimos las mejores prácticas de seguridad del sector.', 'faq_6_q' => '¿Ofrecen acceso API?', 'faq_6_a' => 'El acceso API está disponible en planes superiores.', 'faq_7_q' => '¿Cómo funcionan los recordatorios?', 'faq_7_a' => 'Los recordatorios pueden enviarse por correo o SMS.', 'faq_8_q' => '¿Puedo cambiar de plan después?', 'faq_8_a' => 'Sí, puedes cambiar de plan desde la configuración de facturación.',
    'cta_title' => '¿Listo para simplificar tus citas?', 'cta_title_hl' => 'Inicia tu prueba gratis', 'cta_sub' => 'Configura todo en minutos y empieza a aceptar reservas.', 'cta_button' => 'Iniciar prueba gratis', 'cta_note' => 'No se requiere tarjeta de crédito durante la prueba.',
    'nav_features' => 'Funciones', 'nav_how_it_works' => 'Cómo funciona', 'nav_pricing' => 'Precios', 'nav_testimonials' => 'Opiniones', 'nav_faq' => 'FAQ', 'nav_sign_in' => 'Iniciar sesión', 'nav_super_admin_sign_in' => 'Acceso de superadministrador', 'nav_company_admin_sign_in' => 'Acceso de administrador', 'nav_start_trial' => 'Prueba gratis', 'footer_tagline' => 'Gestión inteligente de citas y colas', 'footer_product' => 'Producto', 'footer_features' => 'Funciones', 'footer_changelog' => 'Cambios', 'footer_roadmap' => 'Hoja de ruta', 'footer_company' => 'Empresa', 'footer_about' => 'Nosotros', 'footer_blog' => 'Blog', 'footer_careers' => 'Empleo', 'footer_contact' => 'Contacto', 'footer_legal' => 'Legal', 'footer_privacy' => 'Privacidad', 'footer_terms' => 'Términos', 'footer_cookie' => 'Cookies', 'footer_gdpr' => 'RGPD',
    'switcher_title' => 'Elegir idioma', 'switcher_title_first' => 'Elige un idioma para continuar', 'switcher_subtitle' => 'Selecciona el idioma de la página de inicio.', 'switcher_search_ph' => 'Buscar idioma', 'switcher_other' => 'Otros países', 'switcher_footer' => 'Admitimos idiomas en toda nuestra plataforma global.', 'switcher_lang_label' => 'Cambiar idioma',
    'signup_title' => 'Crea tu cuenta de empresa', 'signup_sub' => 'Inicia tu prueba gratis de :days días, sin tarjeta de crédito.', 'business_name' => 'Nombre del negocio', 'signup_business_type' => '¿Qué tipo de negocio es?', 'booking_url' => 'Tu enlace de reserva', 'email_address' => 'Correo electrónico', 'password' => 'Contraseña', 'confirm_password' => 'Confirmar contraseña', 'repeat_password' => 'Repite tu contraseña', 'country' => 'País', 'select_country' => 'Selecciona tu país', 'dashboard_language' => 'Idioma del panel', 'create_account_btn' => 'Crear mi cuenta', 'creating_account' => 'Creando tu cuenta...', 'already_have_account' => '¿Ya tienes una cuenta?', 'sign_in' => 'Iniciar sesión', 'back_to_home' => 'Volver al inicio',
]);
