<?php
return [
 'appointment_booked'=>['subject'=>'Confirmação da consulta','greeting'=>'Olá :name,','message'=>'Sua consulta foi agendada com sucesso!','details'=>'Detalhes da consulta:','date'=>'Data: :date','time'=>'Hora: :time','tenant'=>'Clínica: :tenant','footer'=>'Obrigado por usar nossos serviços!','sms'=>'Olá :name, sua consulta está marcada para :date às :time em :tenant'],
 'appointment_reminder'=>['subject'=>'Lembrete de consulta','greeting'=>'Olá :name,','message'=>'Este é um lembrete da sua próxima consulta!','details'=>'Detalhes da consulta:','date'=>'Data: :date','time'=>'Hora: :time','tenant'=>'Clínica: :tenant','footer'=>'Esperamos por você!','sms'=>'Lembrete: sua consulta é em :date às :time em :tenant'],
 'appointment_cancelled'=>['subject'=>'Consulta cancelada','greeting'=>'Olá :name,','message'=>'Sua consulta foi cancelada.','details'=>'Detalhes da consulta cancelada:','date'=>'Data: :date','time'=>'Hora: :time','tenant'=>'Clínica: :tenant','footer'=>'Você pode marcar outra consulta quando quiser.','sms'=>'Sua consulta de :date às :time em :tenant foi cancelada'],
 'appointment_confirmed'=>['subject'=>'Consulta confirmada','greeting'=>'Olá :name,','message'=>'Sua consulta foi confirmada!','details'=>'Detalhes da consulta:','date'=>'Data: :date','time'=>'Hora: :time','tenant'=>'Clínica: :tenant','footer'=>'Esperamos por você!','sms'=>'Sua consulta de :date às :time em :tenant foi confirmada'],
 'queue_next'=>['subject'=>'É sua vez!','greeting'=>'Olá :name,','message'=>'É sua vez! Dirija-se ao balcão agora.','queue_number'=>'Número da fila: :number','footer'=>'Obrigado por esperar!','sms'=>'Olá :name, é sua vez! Número da fila: :number. Dirija-se ao balcão.'],
 'queue_position_update'=>['subject'=>'Atualização da posição na fila','greeting'=>'Olá :name,','message'=>'Atualização da sua posição na fila:','queue_number'=>'Número da fila: :number','position'=>'Pessoas à sua frente: :position','estimated_wait'=>'Tempo de espera estimado: :time minutos','footer'=>'Obrigado pela paciência!','sms'=>'Número: :number, :position pessoas à frente, tempo estimado: :time minutos'],
 'queue_ready'=>['subject'=>'Quase é sua vez','greeting'=>'Olá :name,','message'=>'Prepare-se, sua vez está chegando!','queue_number'=>'Número da fila: :number','position'=>'Apenas 1 pessoa à sua frente','footer'=>'Obrigado por esperar!','sms'=>'Prepare-se! Número: :number, apenas 1 pessoa à sua frente.'],
 'queue_skipped'=>['subject'=>'Sua vez foi pulada','greeting'=>'Olá :name,','message'=>'Sua vez foi pulada por ausência.','queue_number'=>'Número da fila: :number','footer'=>'Você pode retirar um novo número no balcão.','sms'=>'Sua vez (número :number) foi pulada por ausência. Você pode retirar um novo número.'],
 'view_details'=>'Ver detalhes','thank_you'=>'Obrigado por usar nossos serviços','regards'=>'Atenciosamente',
];
