<?php
return [
 'appointment_booked'=>['subject'=>'Randevu Onayı','greeting'=>'Merhaba :name,','message'=>'Randevunuz başarıyla oluşturuldu!','details'=>'Randevu detayları:','date'=>'Tarih: :date','time'=>'Saat: :time','tenant'=>'Klinik: :tenant','footer'=>'Hizmetlerimizi kullandığınız için teşekkürler!','sms'=>'Merhaba :name, randevunuz :date tarihinde :time saatinde :tenant adresinde'],
 'appointment_reminder'=>['subject'=>'Randevu Hatırlatması','greeting'=>'Merhaba :name,','message'=>'Yaklaşan randevunuz için bir hatırlatmadır!','details'=>'Randevu detayları:','date'=>'Tarih: :date','time'=>'Saat: :time','service'=>'Hizmet: :service','staff'=>'Uzman: :staff','tenant'=>'Klinik: :tenant','queue'=>'Sıra numarası: :number','reference'=>'Rezervasyon referansı: :reference','tracking'=>'Randevunuzu takip edin: :url','footer'=>'Sizi görmeyi bekliyoruz!','sms'=>'Hatırlatma: randevunuz :date tarihinde :time saatinde :tenant adresinde'],
 'appointment_cancelled'=>['subject'=>'Randevu İptal Edildi','greeting'=>'Merhaba :name,','message'=>'Randevunuz iptal edildi.','details'=>'İptal edilen randevu detayları:','date'=>'Tarih: :date','time'=>'Saat: :time','tenant'=>'Klinik: :tenant','footer'=>'İstediğiniz zaman başka bir randevu alabilirsiniz.','sms'=>':tenant adresindeki :date :time randevunuz iptal edildi'],
 'appointment_confirmed'=>['subject'=>'Randevu Onaylandı','greeting'=>'Merhaba :name,','message'=>'Randevunuz onaylandı!','details'=>'Randevu detayları:','date'=>'Tarih: :date','time'=>'Saat: :time','tenant'=>'Klinik: :tenant','footer'=>'Sizi görmeyi bekliyoruz!','sms'=>':tenant adresindeki :date :time randevunuz onaylandı'],
 'queue_next'=>['subject'=>'Sıra Sizde!','greeting'=>'Merhaba :name,','message'=>'Sıra sizde! Lütfen şimdi bankoya ilerleyin.','queue_number'=>'Sıra numarası: :number','footer'=>'Beklediğiniz için teşekkürler!','sms'=>'Merhaba :name, sıra sizde! Sıra numarası: :number. Lütfen bankoya ilerleyin.'],
 'queue_position_update'=>['subject'=>'Sıra Konumu Güncellemesi','greeting'=>'Merhaba :name,','message'=>'Sıradaki konumunuz güncellendi:','queue_number'=>'Sıra numarası: :number','position'=>'Önünüzdeki kişiler: :position','estimated_wait'=>'Tahmini bekleme süresi: :time dakika','footer'=>'Sabrınız için teşekkürler!','sms'=>'Sıra: :number, önünüzde :position kişi, tahmini süre: :time dakika'],
 'queue_ready'=>['subject'=>'Sıranız Yaklaşıyor','greeting'=>'Merhaba :name,','message'=>'Hazır olun, sıranız çok yakında gelecek!','queue_number'=>'Sıra numarası: :number','position'=>'Önünüzde yalnızca 1 kişi var','footer'=>'Beklediğiniz için teşekkürler!','sms'=>'Hazır olun! Sıra: :number, önünüzde yalnızca 1 kişi var.'],
 'queue_skipped'=>['subject'=>'Sıranız Atlandı','greeting'=>'Merhaba :name,','message'=>'Gelmediğiniz için sıranız atlandı.','queue_number'=>'Sıra numarası: :number','footer'=>'Bankodan yeni bir sıra numarası alabilirsiniz.','sms'=>'Sıranız (numara :number) gelmediğiniz için atlandı. Yeni sıra numarası alabilirsiniz.'],
 'view_details'=>'Detayları Gör','thank_you'=>'Hizmetlerimizi kullandığınız için teşekkürler','regards'=>'Saygılarımla',
];
